#!/usr/bin/env python3
"""
convert_logo.py — Convert an SVG logo to a packed 1-bit C header for the boot screen.

Usage:
    python3 tools/convert_logo.py [logo.svg] [output_header]

SVG defaults to tools/od_logo.svg. Output defaults to src/logo_bitmap.h.

Produces three bitmaps (one per text scale level):
    Scale 1:  84 x  44 px
    Scale 2: 154 x  80 px
    Scale 3: 499 x 260 px

Pixels are packed MSB-first into uint8_t rows.
Requires: Pillow  (pip install Pillow)
SVG rendering: cairosvg (pip install cairosvg) or ImageMagick 'convert' in PATH.
"""

import sys
import os
import io
import textwrap

SIZES = [
    (1,  84,  44, 11),   # (scale, w, h, stride)
    (2, 154,  80, 20),
    (3, 499, 260, 63),
]


def render_svg_cairosvg(svg_path, width, height):
    import cairosvg
    png_bytes = cairosvg.svg2png(
        url=svg_path,
        output_width=width,
        output_height=height,
        background_color="white",
    )
    return png_bytes


def render_svg_imagemagick(svg_path, width, height):
    import subprocess
    import tempfile
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as f:
        tmp = f.name
    try:
        subprocess.run(
            [
                "convert",
                "-background", "white",
                "-flatten",
                svg_path,
                "-resize", f"{width}x{height}!",
                tmp,
            ],
            check=True,
            capture_output=True,
        )
        with open(tmp, "rb") as f:
            return f.read()
    finally:
        os.unlink(tmp)


def render_svg(svg_path, width, height):
    try:
        return render_svg_cairosvg(svg_path, width, height)
    except ImportError:
        pass
    try:
        return render_svg_imagemagick(svg_path, width, height)
    except (FileNotFoundError, Exception) as e:
        print(f"ERROR: Could not render SVG. Install cairosvg (pip install cairosvg) "
              f"or ImageMagick.\n  {e}", file=sys.stderr)
        sys.exit(1)


def png_to_1bit_packed(png_bytes, width, height, stride, threshold=128):
    from PIL import Image
    img = Image.open(io.BytesIO(png_bytes)).convert("RGBA")
    # Composite onto white to flatten transparency
    bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
    bg.paste(img, mask=img.split()[3])
    grey = bg.convert("L")
    grey = grey.resize((width, height), Image.LANCZOS)

    packed = []
    for y in range(height):
        for byte_x in range(stride):
            byte = 0
            for bit in range(8):
                x = byte_x * 8 + bit
                if x < width:
                    pixel = grey.getpixel((x, y))
                    if pixel < threshold:     # dark pixel → 1
                        byte |= (0x80 >> bit)
            packed.append(byte)
    return packed


def format_array(name, data, cols=16):
    lines = []
    for i in range(0, len(data), cols):
        chunk = data[i:i + cols]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    return "\n".join(lines)


def main():
    default_svg = os.path.join(os.path.dirname(__file__), "od_logo.svg")
    svg_path = sys.argv[1] if len(sys.argv) >= 2 else default_svg
    out_path = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        os.path.dirname(__file__), "..", "src", "logo_bitmap.h"
    )
    out_path = os.path.normpath(out_path)

    if not os.path.isfile(svg_path):
        print(f"ERROR: SVG not found: {svg_path}", file=sys.stderr)
        sys.exit(1)

    try:
        from PIL import Image  # noqa: F401
    except ImportError:
        print("ERROR: Pillow not installed. Run: pip install Pillow", file=sys.stderr)
        sys.exit(1)

    sections = []
    for scale, w, h, stride in SIZES:
        print(f"Rendering scale={scale}: {w}x{h} ...", end=" ", flush=True)
        png = render_svg(svg_path, w, h)
        data = png_to_1bit_packed(png, w, h, stride)
        print(f"done ({len(data)} bytes)")
        s = scale
        sections.append(textwrap.dedent(f"""\
            #define BOOT_LOGO_W_S{s}       {w}
            #define BOOT_LOGO_H_S{s}       {h}
            #define BOOT_LOGO_STRIDE_S{s}  {stride}
            static const uint8_t BOOT_LOGO_BITMAP_S{s}[{h} * {stride}] = {{
            {format_array(f'BOOT_LOGO_BITMAP_S{s}', data)}
            }};"""))

    header = textwrap.dedent("""\
        #pragma once
        /* Auto-generated by tools/convert_logo.py — do not edit by hand. */
        #include <stdint.h>

        """) + "\n\n".join(sections) + "\n"

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write(header)
    print(f"Written: {out_path}")


if __name__ == "__main__":
    main()
