#!/usr/bin/env python3
"""Generate factory_config_data.c before compile (PlatformIO pre-build or CMake)."""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
GEN_DIR = PROJECT_DIR / "src" / "generated"
GEN_C = GEN_DIR / "factory_config_data.c"
TOOL_DIR = PROJECT_DIR / "tools"
sys.path.insert(0, str(TOOL_DIR))
from config_packet import MAX_PACKET, parse_hex_bytes, validate_packet  # noqa: E402


def format_byte_array(data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    return "\n".join(lines)


def write_stub() -> None:
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    GEN_C.write_text(
        "// Auto-generated by scripts/factory_config_gen.py — no factory embed.\n",
        encoding="utf-8",
    )


def write_embed(packet: bytes) -> None:
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    padded = packet + b"\x00" * (MAX_PACKET - len(packet))
    body = f"""// Auto-generated by scripts/factory_config_gen.py — do not edit.
#include "factory_config.h"

#ifdef FACTORY_HAS_EMBED
const factory_flash_cfg_t g_factory_embed = {{
    0x{0xFAC70A5A:08X}u,
    {len(packet)}u,
    {{
{format_byte_array(padded)}
    }}
}};
#endif
"""
    GEN_C.write_text(body, encoding="utf-8")


def generate(hex_str: str = "", clear: bool = False) -> tuple[bool, bool]:
    """Returns (has_embed, clear_on_boot)."""
    if clear:
        write_stub()
        return False, True

    if not hex_str:
        write_stub()
        return False, False

    packet = parse_hex_bytes(hex_str)
    validate_packet(packet)
    write_embed(packet)
    return True, False


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate factory_config_data.c")
    parser.add_argument("--hex", dest="hex_str", default="", help="Config packet hex")
    parser.add_argument("--clear", action="store_true", help="FACTORY_CLEAR_CONFIG_ON_BOOT build")
    args = parser.parse_args()

    hex_str = args.hex_str.strip()
    if not hex_str:
        for key in ("OPENDISPLAY_FACTORY_CONFIG_HEX", "FACTORY_CONFIG_HEX"):
            val = os.environ.get(key, "").strip()
            if val:
                hex_str = val
                break

    clear = args.clear
    if not clear:
        for key in ("OPENDISPLAY_FACTORY_CLEAR_CONFIG",):
            val = os.environ.get(key, "").strip().lower()
            if val in ("1", "true", "yes", "on"):
                clear = True
                break

    has_embed, clear_on_boot = generate(hex_str, clear)
    if clear_on_boot:
        print("factory_config_gen: FACTORY_CLEAR_CONFIG_ON_BOOT", file=sys.stderr)
    elif has_embed:
        print(f"factory_config_gen: embedded config", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
