#ifndef BUZZER_HW_H
#define BUZZER_HW_H

#include <stdint.h>

// Platform hardware-PWM layer for the passive buzzer.
//
// Replaces the old bit-banged square wave: tones are generated by a native PWM
// peripheral (nRF52 HardwarePWM / ESP32 LEDC) so the pitch is rock-steady even
// while the SoftDevice or WiFi stack preempts the CPU.
//
// Frequency is passed as centi-Hz (Hz * 100) to match kBuzzerCentiHzTable and
// keep the math integer on soft-float parts.

// Start a tone on `pin` at `centihz` centi-Hz with the given duty cycle
// (percent, 1..100). Returns false if the tone could not be started (bad
// frequency, or the PWM resource is owned by someone else). Calling again on an
// already-playing pin retunes it.
bool buzzer_hw_tone_start(uint8_t pin, uint32_t centihz, uint8_t duty_percent);

// Stop the tone on `pin`. Idempotent; always leaves the pin driven LOW.
void buzzer_hw_tone_stop(uint8_t pin);

#endif
