#!/usr/bin/env python3
"""PlatformIO pre-build: optional factory config embed or one-shot clear build."""

from __future__ import annotations

import os
import sys
from pathlib import Path

Import("env")

PROJECT_DIR = Path(env["PROJECT_DIR"])
GEN_DIR = PROJECT_DIR / "src" / "generated"
GEN_CPP = GEN_DIR / "factory_config_data.cpp"
TOOL_DIR = PROJECT_DIR / "tools"
sys.path.insert(0, str(TOOL_DIR))
from config_packet import MAX_PACKET, parse_hex_bytes, validate_packet  # noqa: E402


def read_hex_from_env() -> str:
    for key in ("OPENDISPLAY_FACTORY_CONFIG_HEX", "PLATFORMIO_FACTORY_CONFIG_HEX"):
        val = os.environ.get(key, "").strip()
        if val:
            return val
    try:
        return env.GetProjectOption("custom_factory_config_hex", "").strip()
    except Exception:
        return ""


def clear_requested() -> bool:
    for key in ("OPENDISPLAY_FACTORY_CLEAR_CONFIG", "PLATFORMIO_FACTORY_CLEAR_CONFIG"):
        val = os.environ.get(key, "").strip().lower()
        if val in ("1", "true", "yes", "on"):
            return True
    try:
        return env.GetProjectOption("custom_factory_clear_config", "").strip().lower() in (
            "1",
            "true",
            "yes",
            "on",
        )
    except Exception:
        return False


def format_byte_array(data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    return "\n".join(lines)


def write_stub() -> None:
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    GEN_CPP.write_text(
        "// Auto-generated by scripts/factory_config_gen.py — no factory embed.\n",
        encoding="utf-8",
    )


def write_embed(packet: bytes) -> None:
    GEN_DIR.mkdir(parents=True, exist_ok=True)
    padded = packet + b"\x00" * (MAX_PACKET - len(packet))
    body = f"""// Auto-generated by scripts/factory_config_gen.py — do not edit.
#include "factory_config.h"

#ifdef FACTORY_HAS_EMBED
const factory_flash_cfg_t g_factory_embed = {{
    0x{0xFAC70A5A:08X}u,
    {len(packet)}u,
    {{
{format_byte_array(padded)}
    }}
}};
#endif
"""
    GEN_CPP.write_text(body, encoding="utf-8")


def main() -> None:
    if clear_requested():
        env.Append(CPPDEFINES=[("FACTORY_CLEAR_CONFIG_ON_BOOT", "1")])
        write_stub()
        print("factory_config_gen: FACTORY_CLEAR_CONFIG_ON_BOOT enabled", file=sys.stderr)
        return

    hex_str = read_hex_from_env()
    if not hex_str:
        write_stub()
        return

    packet = parse_hex_bytes(hex_str)
    validate_packet(packet)
    write_embed(packet)
    env.Append(CPPDEFINES=[("FACTORY_HAS_EMBED", "1")])
    print(f"factory_config_gen: embedded {len(packet)} byte config packet", file=sys.stderr)


main()
