####################################################################
# Automatically-generated file. Do not edit!                       #
####################################################################
#
# SDK_PATH left empty: this repo vendors sources under ${COPIED_SDK_PATH} and
# ships app_properties + bootloader artifacts locally (see CMakeLists.txt /
# bootloader-artifact/). Regenerating from Simplicity Studio may restore a
# machine path here — clear SDK_PATH / PKG_PATH again if not needed.

set(SDK_PATH "")
set(COPIED_SDK_PATH "simplicity_sdk_2025.12.2")

add_library(slc OBJECT
    "../${COPIED_SDK_PATH}/bluetooth_common/src/sli_bgcommon_debug_efr32.c"
    "../${COPIED_SDK_PATH}/bluetooth_le_controller/src/sl_btctrl_init.c"
    "../${COPIED_SDK_PATH}/bluetooth_le_controller/src/sl_btctrl_init_tasklets.c"
    "../${COPIED_SDK_PATH}/bluetooth_le_host/src/sl_bt_stack_init.c"
    "../${COPIED_SDK_PATH}/bluetooth_le_host/src/sli_bt_accept_list_config.c"
    "../${COPIED_SDK_PATH}/bluetooth_le_host/src/sli_bt_advertiser_config.c"
    "../${COPIED_SDK_PATH}/bluetooth_le_host/src/sli_bt_connection_config.c"
    "../${COPIED_SDK_PATH}/bluetooth_le_host/src/sli_bt_dynamic_gattdb_config.c"
    "../${COPIED_SDK_PATH}/bluetooth_le_host/src/sli_bt_external_bondingdb_config.c"
    "../${COPIED_SDK_PATH}/bluetooth_le_host/src/sli_bt_hci_event_table.c"
    "../${COPIED_SDK_PATH}/bluetooth_le_host/src/sli_bt_host_adaptation.c"
    "../${COPIED_SDK_PATH}/bluetooth_le_host/src/sli_bt_l2cap_config.c"
    "../${COPIED_SDK_PATH}/bluetooth_le_host/src/sli_bt_pawr_advertiser_config.c"
    "../${COPIED_SDK_PATH}/bluetooth_le_host/src/sli_bt_periodic_advertiser_config.c"
    "../${COPIED_SDK_PATH}/bluetooth_le_host/src/sli_bt_sync_config.c"
    "../${COPIED_SDK_PATH}/devices/platform/Device/SiliconLabs/EFR32BG22/Source/startup_efr32bg22.c"
    "../${COPIED_SDK_PATH}/devices/platform/Device/SiliconLabs/EFR32BG22/Source/system_efr32bg22.c"
    "../${COPIED_SDK_PATH}/platform_common/platform/common/src/sl_assert.c"
    "../${COPIED_SDK_PATH}/platform_common/platform/common/src/sl_slist.c"
    "../${COPIED_SDK_PATH}/platform_common/platform/common/src/sl_syscalls.c"
    "../third_party/segger_rtt/SEGGER_RTT.c"
    "../od_rtt.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/common/src/sl_core_cortexm.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/driver/gpio/src/sl_gpio.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_cache.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_hal_flash.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_lock.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_object.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_page.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/emdrv/nvm3/src/nvm3_utils.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/emlib/src/em_burtc.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/emlib/src/em_cmu.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/emlib/src/em_emu.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/emlib/src/em_gpio.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/emlib/src/em_iadc.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/emlib/src/em_msc.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/emlib/src/em_prs.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/emlib/src/em_rtcc.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/emlib/src/em_system.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/emlib/src/em_timer.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/peripheral/src/sl_hal_gpio.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/peripheral/src/sl_hal_syscfg.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/peripheral/src/sl_hal_system.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/clock_manager/src/sl_clock_manager.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/clock_manager/src/sl_clock_manager_hal_s2.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/clock_manager/src/sl_clock_manager_init.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/clock_manager/src/sl_clock_manager_init_hal_s2.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/device_init/src/sl_device_init_dcdc_s2.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/device_manager/clocks/sl_device_clock_efr32xg22.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/device_manager/devices/sl_device_peripheral_hal_efr32xg22.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/device_manager/dma/sl_device_dma_s2.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/device_manager/src/sl_device_clock.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/device_manager/src/sl_device_dma.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/device_manager/src/sl_device_gpio.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/device_manager/src/sl_device_peripheral.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/interrupt_manager/src/sl_interrupt_manager_cortexm.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/memory_manager/profiler/src/sli_memory_profiler_stubs.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/memory_manager/src/sl_memory_manager.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/memory_manager/src/sl_memory_manager_dynamic_reservation.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/memory_manager/src/sl_memory_manager_pool.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/memory_manager/src/sl_memory_manager_pool_common.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/memory_manager/src/sl_memory_manager_region.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/memory_manager/src/sl_memory_manager_retarget.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/memory_manager/src/sli_memory_manager_common.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/mpu/src/sl_mpu_s2.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/power_manager/src/common/sl_power_manager_common.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/power_manager/src/common/sl_power_manager_em4.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/power_manager/src/sleep_loop/sl_power_manager.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/power_manager/src/sleep_loop/sl_power_manager_debug.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/power_manager/src/sleep_loop/sl_power_manager_hal_s2.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/sl_main/src/sl_main_init.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/sl_main/src/sl_main_init_memory.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/sl_main/src/sl_main_process_action.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/sleeptimer/src/sl_sleeptimer.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/sleeptimer/src/sl_sleeptimer_hal_burtc.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/sleeptimer/src/sl_sleeptimer_hal_prortc.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/sleeptimer/src/sl_sleeptimer_hal_rtcc.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/sleeptimer/src/sl_sleeptimer_hal_timer.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/udelay/src/sl_udelay.c"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/udelay/src/sl_udelay_armv6m_gcc.S"
    "../${COPIED_SDK_PATH}/rail_library/plugin/sl_rail_util_pa_conversions/sl_rail_util_pa_conversions.c"
    "../${COPIED_SDK_PATH}/rail_library/plugin/sl_rail_util_pa_conversions/sl_rail_util_pa_tables.c"
    "../${COPIED_SDK_PATH}/rail_library/plugin/sl_rail_util_power_manager_init/sl_rail_util_power_manager_init.c"
    "../${COPIED_SDK_PATH}/rail_library/plugin/sl_rail_util_pti/sl_rail_util_pti.c"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src/ba414ep_config.c"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src/ba431_config.c"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src/cryptodma_internal.c"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src/cryptolib_types.c"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src/platform/silicon_labs/sli_libcryptosoc.c"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src/sx_aes.c"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src/sx_blk_cipher.c"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src/sx_dh_alg.c"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src/sx_ecc_curves.c"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src/sx_ecc_keygen_alg.c"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src/sx_ecdsa_alg.c"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src/sx_hash.c"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src/sx_math.c"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src/sx_memcmp.c"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src/sx_memcpy.c"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src/sx_primitives.c"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src/sx_rng.c"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src/sx_trng.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/src/cryptoacc_aes.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/src/cryptoacc_gcm.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_ccm.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_cmac.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/src/mbedtls_ecdsa_ecdh.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/src/sl_mbedtls.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/src/sl_psa_crypto.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/src/sli_psa_crypto.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_protocol_crypto/src/sli_protocol_crypto_radioaes.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_protocol_crypto/src/sli_radioaes_management.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/cryptoacc_management.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sl_psa_its_nvm3.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_driver_trng.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_aead.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_cipher.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_hash.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_key_derivation.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_key_management.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_mac.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_cryptoacc_transparent_driver_signature.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_common.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_psa_driver_init.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_psa_trng.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/src/sli_se_version_dependencies.c"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sli_crypto/src/sl_crypto_s2.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/cipher.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/cipher_wrap.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/constant_time.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/platform.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/platform_util.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/psa_crypto.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/psa_crypto_aead.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/psa_crypto_cipher.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/psa_crypto_client.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/psa_crypto_driver_wrappers_no_static.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/psa_crypto_ecp.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/psa_crypto_ffdh.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/psa_crypto_hash.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/psa_crypto_mac.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/psa_crypto_pake.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/psa_crypto_rsa.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/psa_crypto_se.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/psa_crypto_slot_management.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/psa_crypto_storage.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/psa_util.c"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library/threading.c"
    "../${COPIED_SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager.c"
    "../${COPIED_SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_attestation.c"
    "../${COPIED_SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_cipher.c"
    "../${COPIED_SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_entropy.c"
    "../${COPIED_SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_hash.c"
    "../${COPIED_SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_key_derivation.c"
    "../${COPIED_SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_key_handling.c"
    "../${COPIED_SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_signature.c"
    "../${COPIED_SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sl_se_manager_util.c"
    "../${COPIED_SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/src/sli_se_manager_mailbox.c"
    "../app.c"
    "../opendisplay_ble.c"
    "../opendisplay_pipe.c"
    "../opendisplay_config_storage.c"
    "../opendisplay_config_parser.c"
    "../opendisplay_display_color.c"
    "../opendisplay_display.cpp"
    "../opendisplay_epd_map.c"
    "../opendisplay_led.c"
    "../qr/qrcode.c"
    "../app_bm.c"
    "../autogen/gatt_db.c"
    "../autogen/sl_bluetooth.c"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_power_manager_handler.c"
    "../main.c"
    "../third_party/bb_epaper/src/bb_epaper.cpp"
    "../third_party/bb_epaper/src/Group5.cpp"
    "../third_party/uzlib/src/od_zlib_stream.c"
)

target_include_directories(slc PUBLIC
   "../config"
   "../config/btconf"
   "../autogen"
   "../."
   "../include"
   "../third_party/segger_rtt"
   "../third_party/bb_epaper/src"
   "../third_party/uzlib/src"
    "../${COPIED_SDK_PATH}/devices/platform/Device/SiliconLabs/EFR32BG22/Include"
    "../${COPIED_SDK_PATH}/platform_common_apps/app/common/util/app_assert"
    "../${COPIED_SDK_PATH}/platform_common/platform/common/inc"
    "../${COPIED_SDK_PATH}/bgapi_protocol/protocol/inc"
    "../${COPIED_SDK_PATH}/bluetooth_common/inc"
    "../${COPIED_SDK_PATH}/bluetooth_le_host/inc"
    "../${COPIED_SDK_PATH}/bluetooth_le_controller/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/clock_manager/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/clock_manager/src"
    "../${COPIED_SDK_PATH}/cmsis/Core/Include"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/device_manager/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/device_init/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/emdrv/common/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/emlib/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/common/errno_error_codes/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/driver/gpio/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/peripheral/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/interrupt_manager/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/interrupt_manager/src"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/interrupt_manager/inc/arm"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/include"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src"
    "../${COPIED_SDK_PATH}/security_libcryptosoc/src/platform/silicon_labs"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/config"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/config/preset"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/include"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_mbedtls_support/inc"
    "../${COPIED_SDK_PATH}/security_mbedtls_source/library"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/memory_manager/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/memory_manager/src"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/memory_manager/profiler/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/mpu/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/emdrv/nvm3/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/emdrv/nvm3/config"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/power_manager/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/power_manager/src/common"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/power_manager/src/sleep_loop"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_psa_driver/inc"
    "../${COPIED_SDK_PATH}/rail_library/common"
    "../${COPIED_SDK_PATH}/rail_library/protocol/ble"
    "../${COPIED_SDK_PATH}/rail_library/protocol/ieee802154"
    "../${COPIED_SDK_PATH}/rail_library/protocol/wmbus"
    "../${COPIED_SDK_PATH}/rail_library/protocol/zwave"
    "../${COPIED_SDK_PATH}/rail_library/chip/efr32/efr32xg2x"
    "../${COPIED_SDK_PATH}/rail_library/protocol/sidewalk"
    "../${COPIED_SDK_PATH}/security_se_manager/platform/security/sl_component/se_manager/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/common/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/sl_main/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/sl_main/src"
    "../${COPIED_SDK_PATH}/rail_library/plugin/sl_rail_util_compatible_pa"
    "../${COPIED_SDK_PATH}/rail_library/plugin/sl_rail_util_pa_conversions"
    "../${COPIED_SDK_PATH}/rail_library/plugin/sl_rail_util_pa_tables"
    "../${COPIED_SDK_PATH}/rail_library/plugin/sl_rail_util_pa_tables/efr32xg22"
    "../${COPIED_SDK_PATH}/rail_library/plugin/sl_rail_util_power_manager_init"
    "../${COPIED_SDK_PATH}/rail_library/plugin/sl_rail_util_pti"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/sleeptimer/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/sleeptimer/src"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sli_crypto/inc"
    "../${COPIED_SDK_PATH}/security_mbedtls/platform/security/sl_component/sl_protocol_crypto/src"
    "../${COPIED_SDK_PATH}/security_se_manager/platform/security/sl_component/sli_psec_osal/inc"
    "../${COPIED_SDK_PATH}/platform_core/platform/service/udelay/inc"
)

target_compile_definitions(slc PUBLIC
    "NVM3_MAX_OBJECT_SIZE=2112"
    "OPENDISPLAY_ZLIB_WINDOW_BITS=9"
    "OPENDISPLAY_ZLIB_USE_HEAP_WINDOW=0"
    "__SILABS_BG22__=1"
    "EFR32BG22C222F352GM40=1"
    "SL_CODE_COMPONENT_SYSTEM=system"
    "SL_CODE_COMPONENT_CLOCK_MANAGER=clock_manager"
    "SL_COMPONENT_CATALOG_PRESENT=1"
    "SL_CODE_COMPONENT_DEVICE_PERIPHERAL=device_peripheral"
    "SL_CODE_COMPONENT_GPIO=gpio"
    "SL_CODE_COMPONENT_HAL_COMMON=hal_common"
    "SL_CODE_COMPONENT_HAL_GPIO=hal_gpio"
    "SL_CODE_COMPONENT_INTERRUPT_MANAGER=interrupt_manager"
    "CMSIS_NVIC_VIRTUAL=1"
    "CMSIS_NVIC_VIRTUAL_HEADER_FILE=\"cmsis_nvic_virtual.h\""
    "MBEDTLS_CONFIG_FILE=<sl_mbedtls_config.h>"
    "SL_CODE_COMPONENT_MEMORY_MANAGER=memory_manager"
    "SL_CODE_COMPONENT_POWER_MANAGER=power_manager"
    "MBEDTLS_PSA_CRYPTO_CONFIG_FILE=<psa_crypto_config.h>"
    "SL_RAIL_LIB_MULTIPROTOCOL_SUPPORT=0"
    "SL_CODE_COMPONENT_SE_MANAGER=se_manager"
    "SL_CODE_COMPONENT_CORE=core"
    "SL_RAIL_UTIL_PA_CONFIG_HEADER=<sl_rail_util_pa_config.h>"
    "SL_RAIL_UTIL_PA_PLUGIN_HEADER=<sl_rail_util_pa_conversions.h>"
    "SL_RAIL_UTIL_PA_TABLES_CONFIG_HEADER=<sl_rail_util_pa_tables_config.h>"
    "SL_CODE_COMPONENT_SLEEPTIMER=sleeptimer"
    "SL_CODE_COMPONENT_SLI_CRYPTO=sli_crypto"
    "SLI_RADIOAES_REQUIRES_MASKING=1"
    "SL_CODE_COMPONENT_SLI_PROTOCOL_CRYPTO=sli_protocol_crypto"
    "SL_CODE_COMPONENT_PSEC_OSAL=psec_osal"
)

target_link_libraries(slc PUBLIC
    "-Wl,--start-group"
    "gcc"
    "stdc++"
    "c"
    "m"
    "nosys"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bgapi_protocol/build/gcc/cortex-m33/bgapi_trace/release/libbgapi_trace_stub.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bgapi_protocol/build/gcc/cortex-m33/protocol/command/release/libbgapi_command.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bgapi_protocol/build/gcc/cortex-m33/protocol/core/release/libbgapi_core.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bgapi_protocol/build/gcc/cortex-m33/protocol/device/release/libbgapi_device.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bgapi_protocol/build/gcc/cortex-m33/protocol/event/release/libbgapi_event.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bgapi_protocol/build/gcc/cortex-m33/protocol/release/libbgapi_protocol.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bgapi_protocol/build/gcc/cortex-m33/rtos_adaptation/release/libbgapi_protocol_rtos_adaptation_stub.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bluetooth_common/lib/build/gcc/cortex-m33/bgcommon/release/libbgcommon.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bluetooth_le_controller/build/gcc/xg22/release/liblinklayer.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/bgstack/release/libbondingdb.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/ble_bgapi/release/libble_bgapi_gatt_client.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/ble_bgapi/release/libble_bgapi_gatt_server.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/accept_list/release/libble_host_accept_list_stub.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/bgstack/release/libble_host.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/ble_bgapi/release/libble_bgapi.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/ble_system/release/libble_system.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/connection_subrating/release/libble_host_connection_subrating_stub.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/core/release/libble_host_core.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/hal/release/libble_host_hal_series2.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/hci/release/libble_host_hci.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/bluetooth_le_host/build/gcc/cortex-m33/system/release/libble_host_system.a"
    "${CMAKE_CURRENT_LIST_DIR}/../${COPIED_SDK_PATH}/rail_library/autogen/librail_release/librail_efr32xg22_gcc_release.a"
    "-Wl,--end-group"
)
target_compile_options(slc PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:C>:-mcmse>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Oz>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-g0>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:C>:-fno-lto>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=hard>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-mcmse>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Oz>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-g0>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-lto>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m33>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv5-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=hard>
    "$<$<COMPILE_LANGUAGE:ASM>:SHELL:-x assembler-with-cpp>"
)

set(post_build_command )
set_property(TARGET slc PROPERTY C_STANDARD 17)
set_property(TARGET slc PROPERTY CXX_STANDARD 17)
set_property(TARGET slc PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc INTERFACE
    -mcpu=cortex-m33
    -mthumb
    -mfpu=fpv5-sp-d16
    -mfloat-abi=hard
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile.ld
    --specs=nano.specs
    "SHELL:-Xlinker -Map=$<TARGET_FILE_DIR:opendisplay-bg22>/opendisplay-bg22.map"
    "SHELL:-Wl,--wrap=_free_r -Wl,--wrap=_malloc_r -Wl,--wrap=_calloc_r -Wl,--wrap=_realloc_r"
    -fno-lto
    -Wl,--gc-sections
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJzsvQmT5DaSJvpXZGVjz/ZQZkQwbq3UY+pStiZ3q1T1Kkszr2dqjIYgkRFU8lqSkUeP9X9/AHjfAOhgMHZnd0xdySDdP3cADofD4fiPdw/3Hz9/uH9///Wv+sPX33+5/6R//uXjw7sf3v34j6+O/e3bd884CC3P/enbu8Xt/Ns78gS7hmda7pE8+v3rX252397945++ffvm/ugH3h/YiMgrLnIw+fls3DqeebbxbYijs397Nt577qN1vPV87JpW6Nvo7eZw1LTbo2Ew2oSEj4Po7cEg/0sopCTfMQ7kBfJ/Pz56tomDnI3BiJbeaXnzENF3G95M37dsnL99RFGkx8TPAYqIFm5TAuSlI3YxeYpN8mYUnDF7aFvuE3vyiOyQPJrVMc1iUA1gS8xDWz/YZxx5XnRKQNyeBjEu00e+r6MwJMpWQZ2gN2zPeNId5KIjDnQvNCzbRpEXjMIuCjBWxMj3XgiDlJEaHgGybP0ckf/4kaWIB+nKUWCrJR4aJ0zHf6D7geUFVvSmgp/77Cx1Ez+is62qM5eGokssEjEGKlj5IdKN4M2PPOWCIJOY9sgKx+jESI/Qwcahst6mn7wwIiIhP0Kq2qYsUskKWK6lqueVtKjIdHqBKmN5OCJflQELbYyJeXSUdWDngM3IVtVpU+omfrYMVfpPiLP+aRqmoUoW7HjBm+JJscIkwMfhA73BG/vRcg37bOLPKDqRP8+BRdlHZ9Pyfpgl/ugsdTlnch/OUj8y/v7H9Gf213dqXO+v2CH+doSBnW90jjyi9kbvu9SCP/9699vXh5uHDz//+dYxGcPD2bIjyy02Vr0FhWa1W0MV4RMg4S9f7/T3nuN7LnajEJQ0M+cJZd1AEbK9IzQD/EyJn5BrEs9OLXHY5rQqJl1POi+wDDU2UYDc8NELHEUMK96IKuUx51St4iiLhJpKVmxKCOizW1vSFMnOHJm9HM30Jy98xBHxjyN0KftP2zDhYOHw/3SlZ0b4gf0Jq3PLIeO8X+MBRqZDnD/nOL/13WOjM1RTWWg+zfJFoo115Psz/IqI84CJ26KHnqETTyJ6mzEUsxqT3sGXf7EYA9ZCGJY2BixNGNZyDFhLYVirMWCt6rCabEF1oIQWIW0ZNO5EeOvaXFvfLrRbjSdWHC+dwo5gceUD6l3TSb71i5bvfmGMer5q+fbBIuJ57gd0aAfKQebuL1+W2p9/1ZoUI4rIOwec0jRRK3sEEQqI9dTxY7DUmNk0+Dta0n6ztFlmsZ5nBZXNMrlnMexZI8f6YJCR5S2MsDOmKA0MRSVp3awQ7BT38RwN0ysyiQxN0x6Xa+3orOaJe6hAnQn2WStbkO6RUdcRDkcUJmUHLMThHCBnTDEyhvCCRMbIgsQMgQUxnPOYYiTsoIVgWyPIGLVFSkyBBaIx2TFlSflBi0FQuI/eqJLkLKGFcRChHhqBRZo9GFWmGmdo0XzbHlWghB+wGHhcW4aV2DJ8DomvOaocGUdgUR7DwBh18GcMgQU5+kYwqj3OGIILYo3aICk/BWLovjfuMCkxBRbo9DjySMkYggvyOrIcryrEsLRRh3vCDloINK4TmfKDFsNAxgmPKkjGEVgUm3hyYwqS8lMgxusBjeoDF3kqEofmClruuGGWJt7Q4mGWDDWqVDlLaGHGnihtRROlPfJEaauZKJ1w1CkmYQcshG+OGpNM2EELEYxquBJ28ELooXV0CfCRhSmyBRYqiMYNTKb8gMUIx42uhEqiK+FbaDweR5Uj4wgsyuizuqo5/Tz6pH5WNauPHrtTFbp7Mb1RR0nKD0YMJ0lwH0GCIis1CQHKZWjiqDwjQOADrld7Xmo/Xtl+7rIlj4cmUjueS5OUBLKAyNuiCUAxH7kEIHoyaEjmT34MVCL1p+VAqUhPblL2jKaFxX/PqHyznPSszEW499Yyp8dBXWPED/zqx4/6BLoh48dyDaHhU+s/kedYQl5/RT25DU/+JohmJcICfaV+fsUa0q/bsCVUhwAzPBPrhk1GhPVoGfHhenigLVwGALfGQd7KZojOsXsWin9wKjklOwTaYBPcOoxkTG7TkSpHUQdNCQ+E51u22CKRH2BGeghE0qVDFe2b0R0ELkLRWSgQxYsuI8wDT2Sqr2W6BwPnsXicCCQl96mAIJqVCA9qobfQQLYdKgBYJD28hyvAl9IF60LqXcD42L8feJFneO3rk7oH2PdFy3e8XlxLgQKRkV8WbZb9I3WNUnpcrVX3LoDxWLyAZPtEWwc4W/RgpVgrsjNxMsbP8IIIv944y+WQpXCsyShAEsdXasQCbGMUAp14sK1DARyZVc6HWyTdRVjbzIiyZ7neZgX6swT7rIXtlEJGLdrntCNcXctxkNvXlUfqFt2dI4EK3TOyXxP69e5RYCwZGZU8ZgR0OonWv7mOBg6wwtYNGkZ+yvIq29XkP1h54ZZNthZUtW1Mvt66OdurbF9WKuQampcBVda6jHq9cTOmV9m2avynVGfK2qLWCkWOV+A4BZEXFsroTdUPTrWqV/AqcY0rPNrbuBXNlBp+KhGCQkFNsV2i/khX47I62akz8eF8jLfARWI1VbhJcKadcFuTiy6k+yMbvdIKRROqcuZhhCpJKAnJMBINFPBEF1o+5Y0xtHwuFWlok+IosHHJQU+VB5PsUYhY1WovInTawg7JGyWjmnOctu9yzWbXxqxmrmq7GzXUGZayuwne3PC2UO4JczZCrNd0hoLYSFkGovlG/rYMndakNw/QMFupy0C1NQP50AirRGWA+eglUNgd28lLgcWB5ZmkTRQC7mQhAzp8cw1olBWaMrCQYWCf9CErjMBtUCNpGZD4NcKBi2z94Lm05iD8KO/kIAO5UnQdDGgDXUF4rONEyHhipa8hgNUpSmnMSAIzcUF8OI3V6V52BZKOBnreUSizoi5mtgSp0ZSyBS3XHgwH10gZxh0B1F+dMpw7AgWzlfpgdwQKYZUooDsCBbGdPLA7Aga4k8VQdwQKZYUmkDsCZoMaScO6I1BYOznIQE7MBZkdwDCWSUL4SFDIGuhK+0hwDdtEUwKWbQNjKhGUACSalNUBhS8dqwUEy8clDX6wbCt6A4RUJyxl2WDUZA3TU8FNB+3SKUUJSNGbL1ZvpAtNRgxiBQJmj+p0JfSUlOCH0lSBHNRy6DozG1kHnuBubjrzy+0upA3esrXAhC7tLBTZgRzipUQTFCOJUOA2pW3ltp5H4LJN8gn2vRSaHt/zaluiSTqcjZjyqTZjI3PIXllgQNZSxBZeSLqcObh0o0t0JeOusA6c5siLly+F1apw5g5faxZYNJnRRghX0L4Uf1zOYZrNG2NTNDpj4tXmzFleQfsVArHh+UAvF3ebLjCfQEuyUdIEV9WIbeLVOHQ7QV1FH5A4djBmmwueNuBt3so5gyq/K2i5EwI4WaSs4Qg66nJZONQUtB+h3th8Fa7X0IrGRFclsT4NFc4todrcesa1eLZT9nqYKpW5Ps1uT4XnlFpQac5jS7P2hxqa4o63r+w7+Qajy8UiJeFoo2QKJ/GBosCzbfKCykROIpgRBfawZJoca55SU6IqHi/OPtcjFD7ZOBIqEMGPrkT+gok1MHtjBVHBdsiYqmgdjQMynuR3Opqg1UlLwqNwbPQmVieHD16J9FB4w3Km+jHK5k+lhHzSDjhSgLBA+Dq3a16PQleogjkldXck75CyjkihlXJ3hApY9EBKbP4vKWrYsWoHK2lIQ+bSlwIbtmc86Q5y0bHDL+BBIVRUqrEr0hJiRTjCLkRJ8XmNpERBsxLxdOZu5ji4WKjVQJiueyULh/GK08V2eAHUZtp6KHQ8EqaRCoyB5RpVFiV9bfxupqiHXaJzyfSr4ZEKsdKyAtZTVT9ISz42coQekWMKAYLfGlWABm6Xc69aOnhcPmY6jkaChykO0MCUxUwtTJXZ8PGRUKRXuY0EPmEFBp3dAjoS9pQXGHh6/MA/4YBMeyOJUOZ4fVNTaQjAmcOKzhKDXmUGOt5GAi95S2P3eBsJu+wNv63gBa9eHYJd8tpVHlMxkgRljgoEEc9QhxGHN5kd1v4xK9J+qYucCYyL/9AImboJJAZetYdlzmMqklg0OC0SYrBLw4ryCP1ZE7dRFRbf3ASntMJQosvcEfpgevkUH4aprlrounYySxYW/TIN01DS/yn1iutZZXi1zmcmCPzUxdRWcSSK3CbXsy03wkFw9iOIJblcK1WzMXp3Pjgb3HBCK9Rd0gj6sxVEZ1DPq6Y31uqI3sTQyFZ5jk1bn68BVa6ENqZj2gsQS2uNrLw0pj5Qe9w9QY8TxRzA2aNNqG7mk7OKDna84G06UcoyHsD2KhNOG6vObnjvK9PMyrUEmEIRLgUFIFYbBICgf4VRUppSsXgdbMFbL8ARCo4YclOeq8mKfMHbCdC2czUQjFWvaMj3PHukDtfDWolol5BJ0Qg6XsDk5Vyvb/E21mBNXNgRxmrSGuNKUuAKP9MR+4zdtFQczQRULRwfgjE7ux94VE0iTmMLJRnXsa+hUnTszKPszYgcrZPyqU59df6jLYwBjBKvdtX1+kyvle5f5Hx1x3laWsjxzxNYefln2PgqIZhNzhntK5yN/TNkLydKSWermPDkQgK+90LM1sUiArVz4INugai2Zkk4+OVDiTzr/emNKO2sQcq+1OhjZ3URuRK+QEJZjVojk4D1jCKh8mzyAvZjuNTMHtoY+7rteb6a8aG0A+Xga51I3aiI7+e5kFg5dzXCgSePi0knfz6Bc/CPMepLAnYAmJLr2WIdYNyf8sBUpfrEJaoxGx6JaBqBY0rRfyWY7HhQLEYDt8m5qtSLRpaId6hq8URQQB/eS8hma6giC4AIXUouWViPALzACSIgVyULNxzKAjSzAmoBP/AMHIY6MoA3Bpsaoc7sCpfj2TCAb+90YV5koWCkqQeuvJ+qFaHObIIzD/ETI8uZQs5EjgXUfqREUxNSZjO8X+X02NIhiAxjJPwlfuCCkN5LaI8pSs4RXJjDeWRZMobgoow5QsoMAbydMmlQ+1uRoonX9bkJBWOlRFfJdFVmA9rOKnFX+Uxuej2b2EZvl59aYxyARiMmmBqMnPxwaxfT0lHgPG8c/UgmtwelqCucrs9EJMqHG2aJlhLTkJOfbOWnFvVixwyeZW9kEdytU9G22PBMiCgx00O6D0RbNSM8OXvpPjuD7sAB0DqFQGvnobMNsTaPlU+JMtVXqQ+0l5ScGpBA4PQjdnFgQRzcatJkgToEWAMZJ7gRV4aa0YYACuM7N8GEKQiVktIfbRSe1EHN6UMABipx0YQVqKAFo+Ud/sCGKtuUE4eA6qOjqvGUkoaAGQXIUIUzow0B9BxZNkT9hiagGe0rO/ZXnFLTpBamG4ggSUFRdNXQzQtiMlcCGQhcMoep0WpGG3bqUQO2RB9s6lGDFah2WXF2UAM0Jw429agBmpKGs+hqcGa0R626w+rLgxh18Qr4/cqJac4q9K8vtGFbB7nQhtiMWw1JOGA7KUwE1leLRAUaoobMcM7QuBKSQ1BheFR4OCqgIo4lWOLFGuu4LGSCd66U5hBcTggOKyE5BJUfwEwdBVQJySGogHbAS7DEd7nruJL7k4CR5VSHYIPa1C1BE9q4HVaTCGJOgZjnqfQsxF0gOnROAcaVkByIiq4+fQQTBSqDK1CWxki3ZhVor0x2iAZRGOIAXHs51SHYDmeYEE9pLIhGdup9Lj7oBd3fMqqDZhzkPJ5dcAtSIDsE3TMOQphkwxK6Atlh7RrAhD5LrRqI7i824gLdPargk9s7avbvgeHh4fYNqGh0CZZ4cegW/x4YV0pzqH8PDCshORCVonm+THnoGgQYXEJy8BoEejpIaA5cgxiPMCGtArKcKsD6CB5bQnU4NlXzQZ368LUcMEShHEeFkUeBzKh61DIIXE8n//Xo6XNTqEC2kgSrKh6ARkvSrGqk43ZsYji5JKxBEWJ6KxP1ruAqlaYFDJI7vyrEJx3aSPDCdav03isB/1qhLTAD65nz4FD99lXiTF4+LxooDB4rYkappf1UIhg+kXxioKVDUSdJt5VYQExity2/+UCurw+1IfF5IojZKZckbZMC7QHRPkYGqOM0Yxy8+EzogDngzTABPPGcEow33gp0qFteogTomncBFvXRL+kHZd12+ARTUEkyvxSJA40JVTBz8kBjQiFQga28idxZzm6v4L+r/L3XcbN5yzf3rmGfzb7PGhsuvluDRppEy2yyL2cU7izhP6sT42qnJkQSMflWQIKB+Aqe6G80D4ksZ4RifA1gyoSkNXMUC5y1auXIHyyr4mBLPGcpdLKlCUeRjgQOWu2THg7cDcRRotONQ725ONhnHHledNJtrDuWadr4BXWYBLkAUH25h6JITw4Y5vcsUVvMrnHQPTKIAkvOxtCVBSd5kZZs0VS6FOdlOROEd+kOEmKD6CJ6023rYARvfuSFXrsfJOE01ZdXyawsmc9o2ZZB0/DRQSyeWEtYKAos4mM0aoz5FZm/UQQ5a+I1KNOiREyghw8GfoEQVEn4A1otVthPE3lB2qxOs2dE1iAtF9CAShSF4MSk6C2Y7D4nV+ze63ZQzXQloBHKye2wgLhKRIVAha86gsKS0xKFcLCfdIMtUMCQlEmKAjJPOrKB+nOJnCgQbBg6IfwM2EZlkjKAnvDbEbugGqqTFQdmhggYU4GiKJyT4GGsTiQnrpNXdRDE3YIDkRITBoEdw/HhYGTkZID4QkVheoH4HEVg6kD8wHKsyIIc1GWSooACF27UJLREIUSQGCIZENQRWmCJQ1jdvlWJpDAgmUNh3Xj4j4F1O59ggMo05Z1PKEAlikOdTxBQzXSFoPnINC0XSEkFYgM8PRAoNZKCgAJ8FNpn7EKS0mqD0BfLaNhG5QhD14KJcbRYx6/JPWMA8llZhLGRuOQyyMSPgNCqZAetzRTAygjLrM/A8OT05EeuxNGIXlCN1CVXbZC4cpLCYBwEiySmN2ABCYmmTHbgIhIaWJm0/EISFleBqjAkmkEJ3IAZSamVLSSUE1dJqwYgL7pgaks/lIyk1FIbEkpKUHK5DQolIym55IYG43PU5+xcdkMCKpOVWXpDognk/PIIGkfUA0TUGf5w//7ut4e7BzFv+F8JvNvoNRoqWMp9lhMU0vAHy8BuiL/gx5sHygDfvweF1UpfWv0l+F/ufn+4u408xx6KuEipjk1i19Y5YDOyBRKCOHdfWzlK7tqyi+d9zyXLpkFp4HYqsR6efd8LRKi10JSsYNTYU9i1OwlAZBiYLBaR6M0j1bYt7M4mv8yK6pzVdZJWPepCI1rMqldcz3EtP8AhgXR5aStgwIT1qRM7iXZtQiJcoAzqQk+4i9BTkaVi4fKKTa+bypmDdJnY8JNmkt5lHiZSjT+IVCknwxDKzQWSqcIdViIHyaUCAYmUsAeVKV55k//KbYXCSFYGATy2jhfphzX+QJMMs+wx8csYwTJ/0KnzgmJVAVxqrpQ5tNfWU9LpalwnJL3yLmcO0kfIDKUjsTsYgIQpcIaxTIZzIUkKnGEkIRPSpUQpsIaxQSe0uJAsRdZQsmjrzeWkKTCHkme90C4nT4E5iDzHi1mAI7AFKPsDF5loyvwhpXpG9lkyGg4iVc5fhZd1CbGqAJR7WQBXUsRtIVDcopscXCwkVqZ0ZiB/W+byl5xlvjRCQXFiPsKXzsNJVQGgQrgkheOS4uUQwAQMcXr0VTexj10Tu4alPKzVIGYHEMjZwYpCXfSOFggBa8yBwyUOctEROzQ0PqpkbQjAOmjOIBkElzGdrTAUCBoFyA19FBA0KTfpkxdAQndAGkcBA05SqVMB71ksKCUgjMyJqSCFNI4C1EfyReWHDO73MnvCb2RyJP+ONwenpYk6uPGUcqnZTwLcOEoJraOLonMgdHvWCPoo4brGaH018SZEkqQa2zU9CkNUdw4jbOph5AWC128Oa0W64id/zrqQyHXh1o48HaH70AAKzlKVx5cwYytphuRGYGvT19e2o2qkFYLy5fXoYnYAUREsecTMyl9A0BYQ6pbbo0rYhkDxcnv0VmyFodh9olfFyJ8vBBK5FZBi4eWPCSoQnPNoYYO4l9htSKWY1FZDgkkPNbWrgFT4rLx7ke01Ovkt40Xt0Mi0WB4XCsY9bZlLiJLwvYoBrfuBF3mGZ09xYFtVdHqASHOpT0eusM33qDrggHXelOiI0Z4WcVuQwDnSZb6qp2S+RgU1RE0avIyULUimZKQmUqS6qnQ99M6BIVB1lrf2R+WzvtNwHV1NtsxEWcLsCGja27iqTTQDCiy5Cgp9iBK6EpAO1tE9C91RwAsqpywDy/aMQWV1+sBV6MtAPFu2yWoAKwFYoi5Tgpv8j22r6W9F2jLQDCUdLiErA+iEyP9pcyWoCrSlofmeLVdygAtcSl0KHqbjSL5cWS/AMn0ZiMqMyCDzwQ6GqQCV0JWq2k/VrCPzj3MY6TY+IuMNwAltRdrNDkqAx8BzaOBpNBGKDAcLQSNmjGBMXL0QDQxBhAjPPg5CHI0qSAPTwcKEoVwNRCHwCZPBYF/X8716tCkXebhqx6f8YGSHXFUgywhLgfrDR0+DdsjbYWWkpYDJVWnqBcVRqakR0FGNp3mU9jSzY+HKPKY6BxmYphJopjSctRo8a0lA2Z1k9E5nFdBqDIaAPEeWkimrxkAGJFl7LJZzJe1bpC0DjWUzYlaSJVQSSapzkIAZWD52zMVGyeq1RFwCHD0mqwJXSlcOkrbeKAKVUJaDJXRbmgAo2dvT4lO0ikAllGWiqKGrpE+ldCUhvRAeSuaCEnGZQCUK8WalJEiZUZby/B0fRTfa7asaz79IXW5hEkaIpqIomuJrDGRARoFuBgc1obcCbQloJj6cleDKCEuBUjKPm9I7QuZJyQIlISu34JUr+tu/3uWo/dsMyY0CT7Lkbh+qnLQMsKFZ3K2wRPK0K6BOT6bcHQQ9mFK6MpBo3RdVZqpEXAKc7SgxCQlZmcUudrzgTT+cHx/pCTvblrwRsm/x28xGArCLI8LEeMKREk1WyMsAtMJIf3pRAi4nLQHMs5TEWRKyMkterGQ6SsjKAHpSgudJGo4RqlkR5ZQlYamJoKSEJUFtVYHaDoyJqQyHyUILkbpIXYG2TIhJzR5IIL0DomgPTn7XLaQJh8g4KVkplojLgmO5CuHZitQsgZp4yEL1vCdLnSIz6pLwIov6Iqrg5dQl4EWnACPpS/F60JWIy4CzHFXIMsoSsJJzkSpwFUhLAFO1dT9gs55+qhuBEttbpC0PTcm4LNKWhhYqiRQUaXdD40sjl61w0HhUFlJgenx9WG5YfDYlyVhBZ/Jv7KKDjUGXYDnMNk6DoSc5LVAHyvslaGEIJQgtkuIjKxh+AJVblDpLKGHCN9dz32BDSq1iFJlNJoGdoh2evB6LS+lElhsf5QmhXdeCXpsZDQc+8H42fuAiN7bxAK+Uc1ILvs5MXoB4308R4Jz4EIDQmV8lgEMS5WMaYBVZOnBKlVzpgetG+DUK1duKboZwgowyBPuZwgmk3Bh2M5QXhBALQANgBcwZbXl48An1BXzDEudjGiqCrgWIA+OuaXUCnPQfRShL9AfAtP6mbPxktAfAi4KzoWr6zYnLA1S5yABYTQy/vqADH+/dBLKHyVPBKjEE2zoEKOi7ZbQz/WpAoYdUHwmKWY1wjy5a9o8AERVpSoGJt3YUIMoIi8FKN5sgERVoCoHJo9aAaEpEheAg2zq6Q+tdVOGUiArBiRM4s6qXkKAaSItBY+UDiDMXgGwFZbDKZGUgKdFWnbQMNMcDiWZWUCVUJQHpAQJJvamDSikPAEY0/oxC4papQ1hiIQa1UKRCTa9rYyAG09WdMyyujKIQkKRYAHScJfMcmsmLQUx1Dd/rGkjLQHsJEMghzgqslKwYJLAYVO798UWcurxR3XJ80O7eTH0IQAW2op2DGNAIZIGdoYp4tj4bTiYo0VGdshAwbPh5AfKBdw1WoTXRlgAHb7aqdMVAxfn7uu/ZoA1ZpSsEynY8mEzoFE1GUAiGY0JVVUhx5BRFgUBPKgWSYlD8EHBjI0NToioMCOwYSREP5xGSBjh0aQsTBS3iyakKA4oCZICanBJRsdAGMqnLDAmmQFIMypOSKaxCVhQS9EAvkBSEAnYcN4fCeQi3JRymprmaiAvBCwgF4g/oJ2zTWkmQ4BpIC0NTobQqXSFQ1URnJQg7mYjDtS3giGOZqjCg2E9W0OMaiQvDc6wQ5MhdEVVKUxgMobdYKvG8m6lLAnzCb+AtWaYsBIzlxaoYmTXCwnNBGkCKhw/wHkmNuGzMXWVgtEZfIk4FuiXIeZFnR8AMHE1GVrJ/qelYAwANvr60o7vzXUPaMRbBu1QjcVl4SV4T7RF0TtNdmgqBImvQbagdiDv5yQoR2l4EdHdDB/QGLtKAk5v/FAHNqcsCpGUR1YBLKMsCe3w0B11X3YEsJS0LbehN2h3Q+G7Eboc28HbjDmRctxS3A2MFQdUgS0nLQqMniNUgSyhLGw9ldmOQvthECRx+qJAeOAerAcdbqb0DHnAeSgPpIdAURLXbOQD5MYrANnCBd7xGgV7mN8RNUAOXqy5zj5ugBllKepCboAZaSloWmop1eQt5aYiw2591ykNcLDXAuC7d6HGx1CDjK+fe4WIh1/Qc8JyXdg5DfEFFACU2vcsumxpc4aCGrS6VFWGscxm6IFcENKfeBhDgFr0AWbbedyCi9lXseokdoAhtnTIT0VYRXJIpNyuQEdsZiL/TnUehY18dEFJSUjBQGOIgirMiiCcrWAe2C1UzZSmQwmeTunBxHkZqgfKIUXQO4NAU6YntAQP0YakODNV7pbuuon4L1WnheuyA7graV7k7qugBuPTyWdGrTw9EVIniO+mYI59LqySFPCNEZhWCMgUEQfHwg5EremRhjHdzbbFeDVF/TmW41DmtWTN52TZRBFIYoVxDvTiHs9TNwKkSGYHhkjMysxpR2UYBRSUCSa4V/vaCngcZKkZguLyMzKxGVLYVQFGJQJJrhdAy8Quyn4Y0REpjuNQppVkTadkWUQBPEBvwyXjjZPmiTgF+DJYaZyM3ffp61F65Pu/sKRS5HvrYsB7FouFlx4tQmTFUswzbrJUFT7dp7zwKEcvD5RvqsJ2OFiQ84v5oQlMVByJngG2MQil7n5JINafpR8NICd4iySZJ5JlVAM56uY061H37fLSElZ6OBZbiHVcfs4jjq/tSVTnbqclbVCbWrJ1yx0/KZsIiRx/Ro7pJJd5BvmIDOZE9/l61lUl3/dafAcAlSERrko4qQ84RAH5RIZDdV6Ad5HyZmlYGBVFkmoEz1gIy+uI2H+aw8Pk7XMo2D47uey/sVvDIco+6g3yf/i/Dqc/J79BNEWsg8xe02gucmKT9H0F+mwnqYDOyDqhT4XgmUf4k1dEAD8zdFJk71KilnZl6g0V1nuxX0loaVjTcZaiRhJ1ya+T7fgeZf+tUQfuCuFCj9I7IGt4dIgu2/SOr9gCkhQkZ0CZtwqks4MK/I5+lCIQ47VD8G/NpoTzhdV3CVM4tCuOFlOdil888taLolZifVmAIE2nrhDkuqSTq/POskGH246you1nhTYJ/VmPN723wCiRfGBFGKs4iilKiDThFBSQc71ErKfHSu2IvKF8BggIBpc/GAEnHd4BGSrRKWfMLCllHokjcE3JNW7buKaCwRRwKRA2to8syNi4pZwmEAiFRFGF2EOCyfbcCA0hQq8jCIe7hwXsdW8o2DKIiCiywyzqpZqC4SrwpmcxZKa0S/LMaawUDw8SPlitZLx1GsCIEBQLKl6sHEk+opr2gcNK33QLJJnIjrqghk0lKhJCvFYSC9svqSUoXfwFqyBoQFS06qJoMVIvyV56RatGkxLF86WSgBq3iUCHq5YVUKp78cWoo8TjPXEuJl66ELyhfAYKqxfgFpeM7piolGsDFZkBCyt12JiFutgi+sLBFHEoX4xeUswRC8WL8gmJWYKhcjF/S4SlgUL4YF/+gvjNj6T4RU/dC1Hfch4McYBiggEt1exZ5ZU1a4g7WWTOq+gEF2MHRpaUr45hSj1WaatzwQ9OjcgMiX6h+2cE+48jzopNOE2B8f4ZfkePbeHaI9NAzdOz4pLESorNutgJ9hJ/tqZMtLYDu4FvHhGZdINzB/udf7377+pCyP2IXByhiCKLgjBsxdetQP6SX4A0lRsbXkcxmZBAGz5aBiUfG/odeHx44bILTvWccBJaJgTiSScWVJoVf2cWK5mcUnf5kOcRoJE2gW85xfuu7xx9npXd4v10M+FYb8O1ywLcrgW+zLsj5fkgrglgGs8/mk67NtfXtQrvVyuPi5IURGX4sueQQ3b6Sfw6ln00LtnWIq0OQ0Tb7cvf7w91t5Dm2Gvof7t/f/fZw9zD7V/L4NnqNFLP5QAaZG+Iv+PHmgb6J7993c01uFKWPa+bKD7w/sBHNKmOF55NW/LEdCPMZ+Rf2YPZgkdc99wM6hLO7v3xZan/+VdNm9zErSADZNZjxAXFqgkNq6dMD4zR+TP9OjtMrZJ3rIPmbeYZw7A5HMmz07HhcfqQXmE02cBWJUTMMKhnQe8YDz7bjhYui1g9w0SNlE+TMYNf2FRZNF+PNsr7geBtOaIWz95Sx2uHcJFnidlxGrZnPY4H32RbO2DGDZ0XmpJUlmYlG4pUIRtxG1yvWOVFqERzLNG38QpaAKX9ex3YEjcTFJWdH3/JGagMfB2wPAIFPJD2jie2SBWc/utBorvMHNpQy8s8QzVOGw9DsXlrwdruZEbBGW5kUtBv7nbpNHE8lrJMidf0hqLyc3dn3vSCaxVuJkwRFWOEQgzrHbVX9VPY9eTUAm56ekoYjWhkHO17wdiETW2E+rn2tMCfkaHxpdBX451F9RffZWY7PEN609ai1dLZs5CYt86azT1r684IQQhtjX7c9z7+wZaXVWhMvFrhZGsoBKiNfLGWnnkmxlp1qXkk5NtVsknpjqlq/ocKPepny6l0KRpjsXvx4y/RxrSx10pB1Ka7AropYOZ5ROVdr74zLOi08cgmus0LlkjH5N1QvGJM9PR4/4ngibklkOaM7aQXGqoIQ3D6RlZSvV73K5PHOkrksRaRKNwNydUbsJISujd4amDrICLxf6KEhi0aAv2VJCdlW5ntN0/6yXGu/flzNeT9++KC///TLHfnPx8+ffrv77av+8NeHr3cfWTrDM7LPLNHiLYxwNQYoQPL9h0/v/5f+8efffv717kuJcmlXSIhBRvvnrz9/+PSr/vnL3QP5Wx7kL3f/fP/+Tv989+X+8z/dffn5QwloEoLPI9PyjH79fP+pRJtG1uXJ/dPPTB0fP/1WInpCtt64IBEkXUNLCQ9DfP/b17svX37//LWxS9Ri0LyM3n98uH/QfyOtqP/z/Zevv9MWlP1S/6e7n3+5+6L/5f7DXQnd//O/z170P9h+o+6SLqE/W0F0pll78S+8LD/++e6Xrx8eiFZ++8v9rw187Oh/FGKC6ZGPP8lr/ePdx09f/tqo8nJYSp7F50//QnTWxKHkYIjq6PPDz/r7L3/9/PVTp7pK986Jq+vLz/cf9A/3f9Y//v7h6/3nL5++fnr/6YP+8Pvnz5++fC1xG2Jd7xr1U6yoIm1lP30pK4VOMKIK+P0r+c/nn1NFx8OgqWdWvXU5fafsPn/4/df73wTY5aUUpXl+/fnPH+4eBCWN3XSI8fjw4e7u89f7j9WekDmJQ0jfJwOmQjr1+vhJ3xOd/XL/6WeiqC93/+/v92SWJR344X/d//brMHzZAGsBWvEKBxilh7v3+qeHynxeSLYvEU6WKX+J0z5j147G6H+YnTwHz/7wXBTOHjLf7oF5fbPnjf7iBU+hj4gH5/nYNa2QeHZvNwdWo48ze+pwtmxzdjRo8DaI8OuNs1wm70QBpVyoUFx4rBPX81CtSzw9QbJfqVeCXLMuTfLDVYkSNLQKu5f1eoSIXdu6GPHzKxIEP9PFW00O9viKxKgJkP4yfRmCyAt1ZCI/Pl/WLopeeXMKNqyaY0pzzlpMcnrxU1G85JrjichQTjPNxWBFYwu46YkFQhcHEwLOEnBbNB9GyHgqKd4jLNyjOZne0y0A+ZWNhJII6cP4OIthW5c3WHDi0MDWlXQvZBjE99ZtK4yqAtGP9MLvkzJYwmMm+eA68Hf2sasRIY6hVmWIn16FEGQ6cbERT9ZnAo9WF28cJU0vXs9wqbn0uVgX9+r5JDghu1EAGrglxtjCoXYdchi1IR/LYVzHqG8e8UyEKQx7+LuQKviTiAz5gOc1rpeqe1CNL7keUW/lRdJc9ic/CRXRP+7Zud3s6e3ZuKV/GSdEL1siL3nseddrt4Z/rsZbk7Yfg/tjhfuj/7y+CaupdmpY2x4i3tDBqmwMBdWj5Dzc6bYrTYLtZp6+dct2bDE7k1PiHp/BFubOTmz38I7fSf7nwQgsPyqx/od0zzcfRfRNOnJv7RFU8nh2k+k2nnZDCMUIYjBRhC7J30WupxvUnoFwpwdznUMv++w1aP4C3RKYs6DePceK9MeAWF7d99jW7SUa39PxK12aXarzeXoQRdbIDZ9WoPiIfDYBji+3Qdx65JrM7hfnwcVuBN6vry3c//t/X2zV839BgUsWNuEtsu0LqD5jj1+jAF0SgI9N5EaWUXZGGuqfKG0E4hKww7rhJWDQNxzrbyySXd7ItP6m2AhAsxad9vHhfCTLoGdcHgQmfkRnu5pF2gzAQU+Y+UoocG7JauE2QsERR1UELa/VvPAbhzz5SdAXH4ghOp2dQwVF8kw98+pC4MYhT35KlgM35mIzCojGJQGBQp/fkOc/cS8Paixym9+LJn+1bXK6CSPzJ94ZqoO+7wuAobXF2uarGBD3pAUMqcl1uXl0vZv46UUAtfhyDFbxt/H6Uupq6W2rT2J0HM6ZBlBfI8ES0VQ6I+tVt+jmX9iTcRWkFo2UXur+2s2/JM8upBtliET00+rH3HwaPNJFNaMSi4hO2mMqN4/0t5v8t3EVNBowEW11R8FuHtPfL6a10QEKjb/uOM7NI33hhr1wk70w8rAcH6LQaG1ZCt1UaxCoH57KkIjooy0ueUNWJdgIf6K/37J/jq0f1cial+8tr7VvK8jvJgxExPQzEe1kLm78t+4gv4zq/0voffvu5iPyf/qH//Lp96+ff/+q/3L/5b/O/uG/fP7y6X/evf/6288f7/7rLfuYA3N8lu+W1g1OtnaqcJPjYJ5fdhDYNinddjU0TXtcrrWjUzuKN0xNVthU2Z0R/WCFUUY4d+Xs729uXgKiGmI7MdaZpgoPHeIIe0btsdH8OMDp85JQvSjo0s2uZvHzYT8abRPiLFelgIJZ4tPVaVhMWGLubkOL1htjnTi0llpsBs3oNj5nZLKUBbane3t0z7fZgDugpKx4QScFcvm7t/ELxCY92ugYTlBnKnsl+ZIuoG6Cl1fSPY8OdqNB3VOixchMJtBmydtpq/1nmw1vs5LNtu1n57pMSi+KwtQKboWrjtlwnTV2DPVmM/MsuQxnacuIDEMq5q0XnXBAk4oBBO79qvFy2i4uDg5DIvmNjd1jdPqp6s6MYOWEVFx8//9OJdfGWGsyi/ggeyV/ZORuXqzodMOWX5BGdNJw1XlWouQMKzDONgpMTFM+sWu8yWUBTEcil3jmZm3dyb+HP8SHAhAj98cEmubHtGAM++u7H//x1bHpq/HxdvLy4nbOPiZUPHrQiTz6/etfbnbf3v1jTCBdoWb5r2fj1vHMMxlSIY7O/u17djDtc/zaZ6LjPzPg1UzhW5aoS8gQgj4OorcHg/wvoZctgYst4BM6TAEPEfb/RKQo/T2SZAAyzdShS3IgHnAUsRyVSYHzLZf13EmBOhtJiw7snNXr8JJIWtPcUX31NrRZ4kCEWy/Qq9wJdWsERloPwghilHQkkEbPxvq3pvuiGjyEntvQRhhSyEfGk36I3scCjdcOJZ2yg4Pm4XaYNptpnuRoNrUNTx2wTOYme//u+3dJgFL/8unT13c/vPuPb+++3H34+ev9P9/pxZ++vfuBdLXbb+/+Tr55uP/4+cP9+/uvf9Ufvv7+y/0n/eOnX37/cPdACPwboZAIdxffx0Sm0x/+7d+/pzfJOd4zNsmfbE79PnvxgVUCZ+/RmY9VX8+vJyrcN/199vMhov+Ir6mIH52D+E7R+Jfiu7Qcs55Yw0ZiDZV7ij/TC7qSwgrNP2bncZBJxkJkhaVLslve5XkhPcfW9m6UnAvNz7G3vmlEgd3za2icMB2Kge4Hlsdq1rV8UCqbpnuhYdk2irxWqcvvRzSk0PamF7T+VrhrRjcN02h7r1q0quXnhFzbW6WaVJxvBfjY0QjlKpctLzXWNep6p1IRqP3VWo1Njm+i1k6f1wkqvEFHeWzOmb1Izf0PHz+yh9+R+cINf0ie/kQs0LtTFPk/zGYvLy+pu0s831kYztKZGLMqUuTN3GR+S+wjfWiZ7O/6TN41gdAPfdMpUfoTndESk8oqO33n05uKg5jf7X+j/6UmNLegqVR/YppJ0BG5KcW/fz/UDKa7b/HlgzcPH37+M7sE8/v8py9f7/T3adHIMGmhll27wi9FI0NnuLafTtWfsgKVuoEiZHvH+ius1kl8W3e8X9v1c+3rchdto2JVBrie/FSjV3sxCpAbstqX7Z/QuSBpj376bOKovTShUfAVO7TCJ77+cUB1mzh9Fv1tMkpOWHzEEaK5R1PTdOkGXfJV48Wvjb8sWn/RWn9Ztv6yyn6Rvh61+2u5W0MH0UwvPJUhkt/KGvdlvtFQbsvkzujvs7uhvy/ecDyJxk5vLP6+dJF0Zy+ALUo3lJVQ2ThAZl2F3cDY9JdeA2PVVxwNjFFn+bKhXIYXGBNAkN+F4hrZIjQZ5pI0LE4iDffdJl8nVwqzHD9hMtIlzYS4xHf/VMHGNSQSW6SqgpkM6bR1I92urNDlScWrfWTbB2Q8hTDkckFhydHQDBBEGjzEkTSxuOOkxOgSWba71CmRdXr4ZFNwIiSFvSCFlcYA2PbUAlPEoVihD4JFb0Ew5UyqhfpGYpiX0gNi2FeUDIANTNkwECA9hb0AeHCW3oLg1F0cC4ADV/kqMT75TCvkAzV+nl1PZdnk2yHE5Gb9ChFm9cDosKlvAJXozcdis3CFQLKlKEvCYo1UmMOGKSYm17K3I0lNvgOy75Ooo7Dr1ECncZNJjpr55iLHMthsYR4gKOJXGhEj5iubxSGoJviI9gaRIcYuCWmzTZhhtMobeYNo2ZqBfAg9+eglAO749AYjzyR9BJZs+OYa0nQyb71o/oTd9GzZ2Wh6BpGrqWoItfqQH0KtecgPodg+5IdQrY7VQbQqY3UIrdJYHUKoZawOItk+VoeQLY5VETqOZZo2fkHEj04iPdmqhG7kZ+kBdIcvDrp5BHZgmewOU953+8wHu3tr9p568/dx/k38SM/SvmUJ0PxO2W85Haam71nGBfG4Jb51/LOOAud5J/Ft9DcWMCGjve/juLEKVzn+EoetH4jrTUh8QIdwll1CmNHPzkLqqN8XHcricA6QMwKTqLeHDGViOGflLNgmGOrv7UMZ0SQh5TzI68SKKGfjIMIqZKe0vV4TM5ibb9uqeWD1HQ2fQxQoNy+PZGpT3v5H3wiU92V6reYYPHTfU98sp8cRmuX0+Kqch6Upb3gLqTeUloGMU693NZSLTQzlGDxeD0i5FU750DiF5ap3YmzM8jmVsxljYNojDEwnVD5ofFO5V+kHyjsWYaGH1pGs6ZWzIh6y8kYJ1Xsu4VtoPPZGsoZyGWW4n0cZ76N4ei+mp7pNioV7FLFy0vQuJeTjvTk9EwiWS5wMOQsj0tpnv8ClJ44kx6UqSg+TlHiah5QxKyVRJaea+vTCSyzyHKvX4nESO/Tv+nFSopVgdcMmolqPxPHj2dHgpsxywsCIcYXsOMlh99w7XXOSCuneARStCEXn3pmXj5ilommT/ZdkYAwcZQmxWIFAtMhsjGy7N3WrQk5Hvh/Sg4wpOXqmqnCwsfBPQQ32UqbalCEe4JoOcBDQmtj0cgPW9iHrCbWnw5hk4zHonZa6CSUtlhwjpMkkjkCrFQmagfWMgxmNV6TweOIjHNQSjIyaHDbsmMFzUXeYtoEktJgYPSQ7MwoHZvk2U/tpUnj0H3CUdK5IggC95GwwIEV2lltoXu6jeEK9EVkxavojseEnQJr0jC8gOe/ADmXBEfTREbLTsGMmgPSoCZe1ogV61Liw4TbEspQoJcMNjl5+FJ/NZWnRGjD6eeeGo8k6Nxy5pHPDEWSdG45c3Bll6dFjHmxWcoZ5ICVKXLuffITkh1mBDMdGKSeZJJUUhJro6qiDkrQrVqMzeDos0OPYNuQhM8CVK9Hh2TnhocMRS+YkA9ibOELDPGQC5NC7BUBIcYR3eejwxVc5KdFcdDBKkGOFK77LQ4gzu6iXFI0fAJhOOk1lM8KQSSohRPEAkMEwZAatCwt0mGkCoENNEwAZakwAyDALAEAnGbcAlOJRJkeIZlj6Jxyg7JAvdV7lPZRmegMmu2aCg8xnK0l5O9pFcqBBLZBO4jaZRgc3eYFgolFgkvI9PEmUnZUqd2VhuuJDSb3yM+A6jSTBxVIoRxqGLDGAbIkmBnGri2xTSfLhOR8Bw0WdSFZddwp6QJVLKtNAVoVKeOmQqRbHA+SQtE6t/N7gdkkopipjqgoLrGLdsf3XV7H9Vw5u6ZZwzi43o6zbqeLroAJPmtcLrcdyjzAGxGW5GHBk3A0hP8B54aLPkV45hHzeqcbhwnf2VoxX2QAYA2KhXAxoh1JIfoDvxkW/0OLDuLArBIOzH5UaHdHNTnbmxyVv6c9WEJ0Hd65mViEtXVL5AZxRorzaDwO3b/sYWuCilWvBpgosPx2BRVKEVgUnq84qwm56kpTWvoHl6gceLWBaY58+V8Qt7SAVbqwYiGwMo4Vn0vkrnUQ9i+zYboDpZ1zHWCHY+rTm/0h80s2QEdglQ24UThEKjnjo8quRV3V4ww6vZh5AjeSfM2Poy8aWi8RS5fvn4d55qapxCrP0cCDgfgZ85fok2FgKBaFtkGZ11YunA/QafnbYWanjZTXKRmvwP9PKzdAqZYXbddvz/Ho/hJaxg1fSJcfkCBJL6mFZbUyYVqSmCFlZmiT9N0RUtI1sYqMVUCe+lIHDUEeGYN5wF4PUWGdaGdbCbWRTrcBTr2gFkoEF36rpvQ95qnr6BJq0pYR2liCekR6q8HbSyXae/D41NxPSh0bgMmD3lZuHkjaxKlwGdqeziW30lo6A+C8YkolOEpLDtNBEktVr2Tis2MxDN3V2D4xtHQIUvM3ye0UO7HmhLiP7O4uWU8rpr30lGkscjJPlxwfhZimx1/gN+ose+tigJ0761NxPM73iZgDZpFg1eSb7XXq5lcARilZSjxhF52AAAeexd+e99VuueHPT10kzDPgUSIcptSFqTGlIajL9XFyZvn0+WjkBdm1TWprUxrqPOn4azCi+oirJDgu7fuuzZJCsFEsVX7ilWiCYnpDBzcyfVnvBPDjxoiWMbwolHqPv0/9lX+pz8vsUcGwmgoNOhA49AzmHhtTS0QYzqF381vf78L4tznKwlJFVezBcjiaiQkiz20RsHP/CUSe2nUKKRZqIhTHezbXFehW/kP89mF6KbSjJ0DLxC7Kf4p/TvwbSSsENI/fiHM5h/Bv75xAqKaIBhP72gp6TXsX+OYRKCoeL0BVftSX+tZXVyYxrBbD6tGzTs7fZegiyJ+QnnjrUvKS43IZuYuErT8XMXhoH+0k3WCIE56mkXormSUd27y5GP5n+fKVeGpiscckrzwB6oqSe8BtZW4NIhw0zRDCU6KpquHwnjlPG/URedI6E814yDoqGY3GwYzg+CBm/N2jUS8YPLMeKLIieGLjDNRxJE6FRqgNaLRaVK5klyfAWMOimssK8tbm56QzBs1xAoMmpSGOJ/6LJqyyLyu3PdROiNRBXPhFKg/KRSWvPyyPJg7FxiSmd3jjLAtHFVwcA5KMvjT/xAqTxlTwAKDJDpEm8hyFICrP+UDKFGX8YqXS2H0LlxFEroZMAm1cHEYjn1KEk/N4dk04Shbl0CBk6BQ75PhpIIMBHfmcguSK9uHkU/zILCze+s13l5DL18OzT+s1psaDiPev03hOyROIqCqYGgee4lk+TGt3ekBIsAHoV/Mjis2xwTLTeX7oIiJthOGNyc5AxIrvjqMKFJ7QYl5223ozLcL3QxmSYPR6PIR30sfUdl+czss8CC76hPK1xBc0deWJQhbxQKJ7EFIzEM31mjM+RWNeRWcbeKvkvv7M4jHHBJozGsDBUxuJpqWWa3Wkfc8iZlp8rsAycnPUAmZanxlC0QUhZJruYDnU4L8tdgfpJr0oKlzJ/LLOPY3Ilf85YKHocVmkMiqzCzmGETT2MvICjciQM9+xc4kUQsHoFWSPHP4hFdIFYRwFyQx8F9LpGWjpMbLdNAQixbbVBAPJHovtmUGx58+BgGIc4LS+mm9jHroldw1LNvOzuqTXhZa7JEyui57f7y7RCMGwb1COzLo6nBAbCyJwADMEgtTogQoFYdTCe8BsZi+zkEsd5lJEAjTtIewCpWTuJomB3KlFTPQ6W+sw0Nlue5EQ4puMZybY5EJx52qEq7g78ZNvCiJ6/VMcrLSOWsRLUnx7GF/+k+QwpApF0qD5SgcWffdRHK3QXkLReyIvCq4w2ggcU4k1vCig3NWLp+u/W4abG6ooJ7in30TxbtqnzXAXMS9FADrZtuO5CQ4xQpE6I/J/We0OZGD3fs/nzoXopYtrEYmkufTRBOwyLv0LRYqd6brTbVziKVHM6Mv84h5Fu4yMy3iQnCyEWj4Hn0BlSDRM69TIOMTd1TMKzz86PKGUUhvyZUkKEX9fzPTBl2CYNI0SDMpYDNl0ZUUCcsgOYreAquMJPDMz/ME9gkwDbx4GjBddBsPGHj57AugY2+JN9+0jRImkCSb995GTC4m3EjnDuwenJ5D/Q0EeLJoFAjkzbARtM2VYqqJvhmHCU1mCk4qpdh/PjI43b2bZAbmkPaZdMkyFxyHEE1jCuRWaxpxcocp4F1iR+f417blK9p9j4KRnhQnhh3kUNrN9RYlswYkkkAZoeqCeSEaUHTsGIkqXVYjmHa5a4rBXLeAzBhi31nCGlDiwy3MzFBmydGsA5KTT/D5CWtt4AUuu9rFOA1hrOsgAueEIaJ+S5RlSIIAsQhGcrgnPYGV3Pe7JAkUYWnW+hKEanACOh4zJ9BC0HkBrn7VW85CBXx5SWbgRg3TqhB9ayMb1w8CKD5rbARUgpNZhYVE4pjX3Q8h46dmnpjcFOX516Eg0ZkujAzYRumvrICuSSV7jZhG+u574NX1QVGNCeElluvMkTQljTBuKVTW54BhInc/uJ813uKEQQYu1aIDgod4mHrhvh1yhU0zmqTJR1kiojJZ2FUA4GO6wFejDB7AJBqAVZgWSIE91C0rT+BtouYRSc+682FyAIbeHlzpekBLOSkbZ1dGWShKuE4r1k8ePhbeTYZrLOc8OxACkC7xmFlkD1nG6awNI6nrQ7U6ekB0g6uNZMDU57hb19OB26unMeTCXZk4aYdzOSUpmLzVTAmiAh9xIg/hPdHKSGohrkkORUipuPQ6UrEtMpFVB4YN3fiKRn05QE2w8FA4QNPz8mIXHEtJkeTO9P9vh037MHy2k7nvymSErEMYfsvheoQIxCxw8HLg2KlAZtgBYJ0fiVvMtYpEQ8bmNwH/KRyXNrYy+ZJ7ARR0hBNL//NCjJMK/VmawbBhrg8l7LUGLSZzDbKUmdkOgjN1T5OTkY96NOEBChbUmcGOgiCLBqqJADMogFqkl0gY5YmoemjrLu0tUsiizh4xBSPODkoEk9cIgHpAg1UHt8FD8g30cODp3MGaU+cnDooLy4IsnhLliBmsTJoR5qcNhY1hwcuCFJeA3kAuSangOyTCpSDXsvGxakBocthGyNELItQtuLBpzIE6AMiDk5Rg+IVe5gfhNFKAeUVamHcvoDVlsw0k/YhnAjKDkoaNV0C1jCsdMIQCkOewDpjxJ0rHCwxWcJIHa4WILNljnFJ/w2WM48nWTggGDZC8IdI8wvdu87epi/mRTnyp+MzE5HERkFkdg2JRBrqbNWULzFFoxQXC8iq4kfLVdgWw6IreihBSC2QgsDIJ5ZTFnIjAExl8w1AOR+Ih62LZJ4B8Q7r2MwMmOxfXMgpkIZzgN4WkWmwjV9oBiPOf2WGDvIsg8e/4FYKb7pDab5tM/rssCwK037I7MWDP4CcU1no5HZCkW9gHhKluEB5J5NCCPzFi9sA8RYaBk+gGejpVLAl1WywYbuhcgulHpLnqiwjd0c9QMKsIOjnLetH4kN05Mri0l/Z/9Ds8QDh/V73XvGQWCZrC/8O/nE8cyzjb+9++Hbux/9wPsDG9EPHz+yh9+9OrYb/pA8/enbt2/vTlHk/zCbvby83IYWvSPjloAlC9bZ5/ilW0y3YOib3yWJu+yzKDjHDy2T/X02bmO+tyGOzv5tJvED+9Oj+dxWSJTzdnM4atrt0TDY577plOj96ds397vvfmQ5d+ziz+98asKDmOvtf6P/ndGXfpxVZPsT01eCkUhPKf79+//IHt29sjS+kPz0b1RNRM9Ecyb58xHZIc6/fWCL5Oy9SajzPdsBS2h89sLoz/SwwH+qdaBa/1OhwAolS3B0tumgpzfDhv+pz4H69MnywPPsa9Xjt3f0uNARu7Pb0DbYLjWe3RqBkV3TFUxp0job6fdXr2/mNJiHxGeqPj1NSOnIR8aTfojexz3iUpr/93ffvzM838LmXywbh+9+ePdvpC2I0uh9NUzt9DXyXULsM4pOTHOpbsk64AkHj+TjW9tkHLzAOlpkaZ+9yp4mpy3JgwX5ix1wcSP613q/mW8Xq82S9YIi57TBq6xbHdPDEfl5Ffj4ZOGMKHJGWijCrzfOcpm8w9LxZgG2MQrZxkDhMRmv58MtkpDlZr+b79brxXwxjizZrzRTiKzJ6gIlP8hJs1gtV7vVikg0ujhBQ+OwFCsZQRbbzWK11fZ7bWQ54lVLXZL4uWQX2+yJIJvVfGRZ8DNdx9VEYY/lWkXbzbfabjUfu1VqMqS/yDXIbr9YEgs2kvkKIi/UkYn8OLjXLoxeeXOAVVtsd8v5er3bQtgB+4yJaxedkuxGCrzNUCdvlERMciKlOtxmsVlvV7vdDlIMG+snso5qk4H4fsZTSQTPpXvYpmxb7LX9crVZbS8rRPKBpAyL3Xa/22mr1XgykF/Z+KhKEQ8a5iAm6R1yIi0X881mv9JAh8hgkWj4DAdSIpFetl2sV/P9RASSa5flekkczN1+PClo6SM/0m0rjJpGjF74Xd4kb5Yr4jBvdhBTJ3/jhG9hhJ2qVPFTuebRFsvderVZLMazBIS7i414Rjwf6KWc7rGxoZpelG+x9XK+W+7nq/HMds2JzgWT9KNvtPl6s1oTT3o8KU7IbhSCPKfWzcKhJifLdruc75fb+WY8UYyaZYtFMSSN22JJ/t9qsV9B+J58MjSbACbGEDuw2y60zX4N7tRQFoFn2zgoiPN61LSiBDSCYaM3yXlysSSrmO12uwdYkGXnztjYLWypsU2wmcHOsFd2KUsPizdhiM6U+/1qTUYEQOhCQgyrQQ46xpPtQNGBsV6SaV9b7gCmfZg2ie2VJtU0S7K+3Kz3EAGywcLI9S1tud3t5/MlgLsC0LcGdKv1aqUR32sKLTGkR93Q8UEEgZjHhQRJst4abJZMgyy0/Xa9Wmur7QTEkOtS2/V+MZ9vl+p7VJJBUelSyVMmiVRX2q8Xi/l+vVI/bXQKYDpICv5it1kSJ3C7AnADh+A/+pYnJQBZQa022/V8feEe5BNfnOb9IVvOIpE5brvZLrcjzBEVOZLBXBoJMmN5SfxXbblQb4s68dOBIGVLt3PiZ+y0hXo3thO/pRly+FfbPZkO5hB7PEPwF8aB1ISwnK/o9s5udHvEOn5YHQk6fgyWGl0xSVonMrtt1rs9QHxHTBwyDsqjQtZXWmxWy+V6s18CRHYFRWB/ho2di3l/w9qGLJLmG9LZNqONeOroVYc7XRuZhik36G+Iud0Rw7VXP/mx8wrB2Y9K4x6RNwwntOilvZahP1tBdJYc+YsFmT/WZP5TP/LrsqQLpdovknPJYr8ng36pftS3iVKXRI+jWI7cWCHNom3Wc0397J7cqFIRp/xU0sXaz3d7Ys0W6qfIRiGsihTl22IFN0DWu/V6s4bYdQdoD933PHuIODdkmlzuNgtthNHPLZDcSJnPScPMF+N3smRiqYwUKfu11LT1cjcfYWasyEDI0ky62ohJn7P9p1CqYdabxWK52O3VL9TbZEpPfVRkkozFLYkxJk00wrrX8c/ZKPHP0jG3xXa13GvrzUa9I0kRp8PBP8uNgd1mu95tdzv1aH3vhZ12yu1RkvhDL8Uu/jbIwmqLzX5F1rfq+z+/PNhZyQmz2+32c22+vagwVmPr6MkdUJJO8HY935NRrd5zrAsW2hj7uu15fq2lZGNaezKKdtpW/TwiJE1cfkZSJm2/XpKRtFTvqPTIVO1+Q/rdzYp0uu0FpEqsdFPzSI2f/Xq+3a52I2xGN8lRaRLJpliuN8uttlM/sdPpEVluNrmTfw/YQF/sNeJgaXuIjDlJ4IlrJb0nuNktSO8ZGb5Vxy/Tb9ab1X45grfSpHtCm953qCOjcCJfOLeKLM3JgnaEqS8VIXURs34v54lv10ttvtteEPiQfrPYrLU1kWCELdgm+JWuI7f1sVhp+/1ulJFLJmB6h0BeJCF7Ims1icHUlsSruCh4Fk8PIsOQ2+bYb+ds7F5ehsOZSCEXIFjPd9p6tVbvAtWEsCpSyE0ABPt6o35FVECfFnHKx4BcGsuGeNTz/QiruRp2ayj4m91mtZ2P0GnOJrbRW9rr478kI5Q74ids5urtfRNkHQXO88bRj8TUPEiZmjWx9tp2NIUnfTxRuFQXWa+WS229UJjagR0zeE4jExQxNjxTMgQxJwomHVpT1z9itO6zs2RY6T8koS41ejJvMSpUnfGx5HZst/PtYr7ardStkZoQF290Fj1uu9ouSe+FOLchAFg6RXWz26yJOd6qHmo1uPqjnRfmFA7Natpiv9tBHJsXQO0dWPkGuUUPcVtX2nqjMGDUBNlHR7l+vKb5vpuNwjTHJrjFS4/E8K7Wu+WW+ETj4qVl3kLJDrGaL5br/XqubhFWQExdCoY4KTyUxt7jYhyyK7HddkuXAKPYjlQC2c2cxW6/2S6W6vIxmrSd2znJYxC7pTbfQBQ8EACdmDkpV3mx2y7nmgZRAEQAcTwMpVS82a1JD97vVfYLWrGAYsXOkNX2brXbbtYKo04loNg5S8HcbrXVnPx/lR2gAFM6DZ7YXjK7zVdLlX5aAaiFTLl2v9lqW2293Cs8mlYC6oSSONfUISPTwUgjyQ/kRvxiT4Y8cdA1lb5jAad0jPBmQSbX7X6/UjpnFZAm53Gl4plzbUP8RYiz0Z1I2Uo9taKSwfv9Zr0GqVDFgxSFIQ4klwzbzU4j60iFB2wrSpXzZBfL+Xq1Xew2Kh3ZAs7SJYeiGezabrFcbhQmTZagBsh5PLuSqeorskDYrxcKT0KUsCY4pLBqxOzvNjQDcqwuEOBBUaXFesEqUyxUT6oJYOpNyZmr7UojMwBE8TYenMydklvOzvfb7Wa7URpaLCB1QslhRcb/fEP0qjRcWwbKypojyVlgt1/MiXUdy2T5geQssF5qmw0ZVSNNrMytkkw/WOy3i/VW4X5OCWnsVg0yV2R0bbbECKg8dZzsheAgcL34PnSdbomEsRjVp5L7Oguy6NIUzhJpqmlS/sBjdyLLn+KhfWW+WKmMjhe2oBLEknH8zW6+2SvcJokvU57RGSLVr/zie76iZ5+1jTq9FuEmyh0wuWnL5Xq3W+/U+WL5Sc0UbpycITfSiLFYLXZzheaiGS+xdcajZCbqejMnXUJhaY5WyEPN85osKIkLrDDmVYCejD0KXXr87YlNW242CpN+mwEPiDCs52QpvF1B7Jaw87ez9xTvvctqxydHcqmbJn3AiEwU28ViQ/5PDUI2lzlLuY3/G+LvkNlhq+0AhlcDOnrMieap7GTR7Yl9hTnKXCrn5limaeMXFOB0ouW9JGgmcqGQlImmdSz3K4g6ONn1SsTrjG+UDj2Djbs8R8ciX9L9PnQIWRZX8VXJQjgs62W+BuhR7QIc0Gq5yC7BkIC5XO63G7LgA7Ab7Sjjv8jj5CJIKV9zv9mQHrGDmLPbkYav+sF+Kl+5J5o8TOYOGphSjdM86ciWPHS03c4X2noLUeahEyM2yOL+HDzLtvlqS2PR+znAJlQvzif8RhhI63Sx1OhZlQVEVcEerCa7Ll6y6ferzWJJZmGlA57APMnu6i+2K221Wc0hkr87EZJZShLhZrWjZ0Uhyq13I8SO4fiyG/dkBt1A5Pv0QvTl8oa3y+WOeF0QNbc7IfqB5ViRJW2E9sQ51OZziG3GTpyBK3uEdL+hWQVbiKPYnQgjeYgsTWezhMgj6fSGFgucukNSqxTiDS2ILpUacQpzOQTlzZKGCYkJAghndcNcYX8Q0MVmSzS6X2qqkeZesFSzL7Z74mksN0q7Z/wXLZ1WuaxbNExMlqkrxabdR6aZ31AvGD7ZrGndSdWeeoCPsnH27WK5mmsQ1+80A7SyqEQcMdHxK+VNwEgi1ubL5Xw9X8wBQlI9kLO1mokfZdW73a5W2nJErPG6Ui6uutL2i91W2chPwZL5E8luDJEJabdYaxD1k3pB5uvfYakkBO5+tdSULd0KkGVrtN6sllttr60hcgd7QRbWwnImYDGnq/YFRMEpLrCFBbHczvyKJhPNITIeOPCmi2LJpIcNO3uifkagWOk2sVwnoLts243CpXEB5kn2+BGZpGgQbAtRt6Mf5Ysuu6N2Q088rPaj9M9kJS8DU5svtjQPW13EpoCzsFaWUin19ffrhbqAXQErW43KaXS13yzJ+klZ5OHD/fu73x7uHmYfLAO7If6CH28e6Jv4/v1t9BpJgN7NN6vVbrtW5gJ8ufv94e428hxbLhFvuV5tVxBVKjN4zgGbkR0WT1LHv8SpII7vuYQ7q/wRv6mHZ9/3gmgWLwXjWjjJT/SaOJuCkq4Kst9viR8GkRKpRkLPcS0/wCH5QtrDoEcUFhBFf2BF9OnkPrgBd+vtRtMWi8uIR2VIsm5oegX5c5aGAYgpO4cEiR5GXiB7InWnrbfE29pArroHSZfVv4aS8IYW9N3OQc6ODxcx7ZfxoyFrpRti1zVtCep8Qon1iFFEpi3JtfVuuaCTwhxycT1Isni6I6YklU/aibhZL6hkC4gcPWjZogC5oY8C8u6AyMiSLDbJcgMi40xcwFScLFeV/SVbK3g/p9ei7iEKeg0QpdxQspnOS1pacw9RqB1MFNosUtLsacl54ohfZgilF7uXeppVfa4HyLQ8JLt7SGes9WYHUmAIUMhUqKS0qEOdRjn51iuyMtH2oPku4I0ouSs0387n2z3E6SLFTScXp1msadUVFSsaPfTOAbtOJEmATKSWjYATR2JOSwIqsHptUA/W0T07crmL2wVZR4Fu0PWANQw5pAtaHZwgXShwqVuxnrDxNGi3lm4rbNar5YgdN8kIlJyz99s9WZpBnD7hxusg2aOfpD9o8/0acpuhDyzrCzoy/yCLRN3GR2S8DfOS6O17ZKk/qsabhHgMPIf66nJxSnqH90YDueZXToowlL3Zd0GvUd9pECeCBKHLavtmQW++XW83Kqb7NszY+MNHT3LhEG3Fjr9rI6oYG3J7GHQ61NY7kAMMvFiP0lMiGXbafD5mN3BMOT9js9+t16N6RY65lnQ2NRo930PUZ+LFmp29otV45bcyN5sVRJEJYdS0apdcrb/FiqWDjjjYfM9+o4VOJCukbJf02DPoTmwf4PhyE7arEMpudm63u+USdF+2B3Vg+dgxF5u5ZLhlu1zt9ssxFybhCS1kU95o/ZHFCjQzqx+ttt5ILkpolRdajXdUuJLnHbXlZr3Z7cf0HQhYMrPKrf7n6/16tYO46I07UBG6ixfyouRe3H65WGqweTr93m8YIRrwl53s6P7vnq42xuwVRhToZnCQ3IPRyJxBZmfQtO0ewAPuklpri91iuwbN2u9FK1t+d7Ffrmk5sBHDAOZJzmO/Waw3ZF7TRu242DAl0+P2+/mSrjNHXNUTzoHnS97nQ3wGsjLegp5/6sNLUyQl99LXW21BM0/HQ3t6MiUz5TW6vUAWRqBHJfrQOsgYYHIX+9V8t1svxowP2o5szvSalobdgObN9y2Q48t4D+fHRxzoyLY9yZpWuzlZEgEfg+3B7uKI/GQ84Uh21tjM19p+qY3pBHuWXPCE1Wen2WAqMqZal51Pkh15NV9sFjuIi0/5oRqhbKxnvqcz8pgbi2nURHJhvFyviFkDPZ3aA5i46bLn625ofbD5EvYwWA/c1/V8L+k+kCG23+4gqtqJgNUN6brC6/V+vllAXL/YB5imSSZZJoezZUfs/sJBGfhkiU2mDYiCfALYsxRIguI1igtFeSFZPEtOI5vFgtb2HSNW3CHFE37TTczihPI545vVdrvfL8ftS1VJhp7qWMyXyy1xR3YjZAkUxAhxIolkQG6zp3f07EeYhYqgo+AseQnSmqBdz3cqEi5TwLZ1CFDwliS3DKinuV3uV4vtVsV5jxasjifr5y2Xi/Vyuwc9OtOCNTk4+xIguY3Sm8Vqu1nu1aQVV8Fiw88T9JEt12m11WJPN0sVjrIUr/8kr9gFmdWXW9hyci0wA3YSNdJP2Pax5EFPYrXm290S4sKIXq0SuIntMmxLNg9UIx7Tniz9VCaSNRgv0n+fUUjmCFnTQLrEfAlSaJfPNEjWEqS1gBd7iDudRSyYXOEpMoUtl0uVi5N615WDulvQQjrbEbpsYZAhjEy5Uo3EhG23G5WL1CabIN9tbxaLxWq1WUHcIS2AOPF+aQ+m9ld3qVNGfHi5Op5kIbhZbNYqXd8GGULbi4am5pPFx3JF99BHHYnZCT+5WmtLuvbbaCPY4wJkmtYm18GXK3oMbDOyCXl8NCVvTKT3Dy5WC20/LmDpYpA0d3pJTN5mpTAW0AA4kEwi3az3tOQJaNUbcWshueO7W81Xqz1EjDlAlq1nHkVy6YSt08eyAVoyT9P7a9VgY8+cR8mE0c2eOBI0TVAhuPiitOFXjKyIe6YRhxfAkyxhTQ8rzQ42TptaJ/+W3prR1nOaUqUKpoUx3s21xXqVoc0fyS7dd3THbgFR0LQZ9ItzOIcZXvaXbEBvR4c7RAHbElJ0jjxCLbZR5HmAbYxCnP2NH4Ol9nrUNP1oGOmvt0hqSbQjywyaoQKtbPtMYGRKpkm4yf1UFunOuo86fpILoNDC5os16Bn5ECfTQdB7zjB/MzlpnT+RrH++mc/plYeQXqeUPMklJvkT+YxqYhPodXhz0DL5A4SyilINK9GwWWtk7lpBOtxArZWFJp/wm+Q1P4vFnt6kNMVWG1gCdrshcu1BtwqAmm3w8U56m9t+sVzuQA8wQEk3RK7VcrfbLUCunQKXa8D5Vm2/otnOUzGORbFQFGEW/JEvY7ra0T05yAWdgGysGA82dC/MbuUqPNEPKCArvkjWiqyWK41Y//3u7//+7vt3D/cfP3+4f3//9a/6w9fff7n/pH/+8unz3Zev93cP7354R8T3fOyaVkhAv90ciBfHWPzHt29EaPSMzQfipT79MwosRNyhkD7+gf6HvkD/3zsfBdEn303//CH9B/MKKT1D07TH5Vo7Oqt5+uP36T8Mz7cID/Ppg2ewBq3RadN8+vvf4/9QlfyCH9HZjq5UgL+T1iJt8z/v3n/VHz79/uU9a6Af//HVsb9LGvunb+8Wt/Nv777DLlktWu6RPPj9619udt/e/eOfvrk/Jr32O/KJG/7gkAWlTd44RZH/w2z28vJyG1r0LqRb0hdnYTh7iM6m5d1iuudCiJKvfbIcfXsgMuGfsjHw7R0h/d13Pz56tomD71zk0B9jk5n8Vvv1ENHfs1/p75aN01/ZFVMxgXNS+i394DsyXsgb9O0fZifPwbM/PBcRqJkSY9Cz543+4gVPoY8MPKt24bTKXEx11sFvluKfxQJk4hTghnTNm96vlU8VsFBbmMyaACHfT0MHquA0smgEQ02bTUZYZp290LBsYgG9QKWyOHjywY0CjMcDWuHWBtH3XsjLdfcEHF0bozZg+RrZjyyVwNoYtQEjAzoKbKXDs8qhB0pIfGbzTO8J8APLYz6CenSdTBsBu8/Okt4KQGdOZQBbmLRqsGgJXTIHEZM9muWt82uEWdxNVYSskUW/zpBJ3IXICtVajh5+HAYE6RFzyUYyIw3s2kewfvLCiEiG/HidoXbodnDj0GPJhFuupW4Y8/Plav6x2p3DJYgvTVfnBJTpt/a7I/KVzqpVBm1AQhtjn545VmpCGrm0QUo3TBXiqbPoA5PcjzsCphqnNmjZlb1kPJqGaagE18GrVXPxSboRXNtWTpzQAnxUbPj7GMZAS0vTyjo72ZprW4bfhrbB0qRw21L81giyViP/BBMy3TPMEcxqrHjW3j//evfb14ebhw8///nWMcHhVcn3Ole38Cqqku/HANcXGzG0DZEvX+/092kUM1SAos6gfb5O3tINFCHbgxyfBZ00smnDhJ/piyfkmnYcc4fHU2PBh0VJn62xaMFiVaZVPaGhRENdzHjxsTrrrFbXqEgb2fLFh5S2cyurVn2yZesYbd3MqBNXeiBzNHztDBtx2pb7hAP65NaGn+4q1BsRUHTJToCFQ3AIVfLNGGjA3jwo6NAFyp2c4TtEgXK/X2c5ZLQVvLoCwgAj0yE+t3Oc3/ruEQwnYzmrUW/UUv7WQimGBRcGTSkGjQvDUimGJReGlVIMqyKGrr7but/ZskiJF5FhaYVSeiHdTi+8UXvnF0ak9EbtnQeLwPLcD+gQVl6svXr3ly9L7c+/alrtxTpVlsDd8F51BopQEJ19PdtWBrRurdkJiW7zjIRYT7OCKmaZrLNYlFkj0lmvfG9hhJ1rEK8BaF26yqK0tfnv48Pi/e3fmE4AOM8AKSmRZ9YKt7cjZF+mNyNPXMAUpoBgh3OAnGsQLQMqJlxkXIlwMVAB4QznfA2iJTBFBEvvCbsK8YpgBYSkMeZrkC/FKSIa4eA+elchXQ5VREAHkS9DI7BI00PGx9TJWUMsIq5v21chZIJTQDR8HTYUC9tQfA5RXF9s8rJlSAXEewwD4yoMTAZUQLijbwRXMTdkQIWEs66i4VKcgqLp9Gboa5EvAysg5OnxSkZeBlRIuNcrke1VVDRLuwqTksAUEQxdhyOd4hQRzUDGCV+FcBlSAfFs4pVeg3ApTkHRXg/oKtYGRawSItJcaMu9jvBYE2YRkTHL8LsKSXOoIgJey+RuS0zu9pVM7rb45O6EVzEFJjAFBPPNq4hNJzBFBAuuwmAmMMUE00Pr6CL7WgQswhUQNIiuI0Cd4hQQLbyOqFgoHBUL30LjETLBUp1sGVIB8a7GO5HxTc5X45ycZbyTq4nXyoRrX0zQtGZlsqU4+0VzkgMjE5aqCFE85WWycjUh5c55aXzc8LD2qHqwo3rOozHLS48LJOrI9ztywsivXelgMY3udDB6OrAvDywvg9CYCFboC/mbY/SCJmXRmg1pdUkqW6GGw6yMrqHlK/nl05amBrAq0EV67LAERp4ea7lGQ4ettFzkOdYoPnZF/NwiJX8ndZtyQLVWqkA/WJfobW24EzR9oGnVVt2wSV+0Hi0jq0k1ESFa0PUIZU1bqlZ4fW2F3fMokRHOxknh9MG+mCFuHdLthrc2Ouh3E4KeA+KA7luwJ/kAwGeQ+uCTYRJOqc9keHqBRyg6jxIG40WeAZr1+RP1sxABx4wdj6YR0uX7BE5qBeeAetvqLTSQbYcTAl+ExDdGJoQ9xdPb0YY5rnEVkLQAeYffWn+DwydtLGoyxngui1WoCp84dCmOWRdcayp4rWbAfS1fb+yzRc96trfg0ai3YGVpEkT49cZZLvuWy7FEUYAaD0RVXk4KxfefnLGtQ4EwscfnA60uP3LzMD3OiLJmuT5mBVyzQln8JrjDwi18Y7Ol+RwHuWaLnrmbpK1REvJTaZHs1wRXvVkKgBsjfK0HvzhPhMXVVFUpO8AT1HTQ0PtTqEp0bDYd9wTTchICnpqeY1h1TedwleiaFfpQpWpGfHKaZqjqis7AKtGz+HyY4p2c/mqaKyIFngiDyAsLpRNV+B0per3Ca1KuSAVbexu0SjGxDaFiUdbu+Hp1ld3g0ic7CyY+nI/xNtgY676qCMlCrx3QrE1VveuuHplHWc9Upc0XMlUo/HKS7tu1eKmvbjjWNyIrnIY1TuNWTeO7ojNiEp0cw6JU24rwb1vipDfWFQ1KjhRiLhzboNiYVdwdYlGihrLHo1qURIbcpLQgmvWIUa94fWkxGhH1iWG+kb8tQ6dllszDVERpRdUnjq0ZyJ+KFFUwfeB99BJMcHi0w+oVCAeWZ5J2nKBQndD6BAvfXGMqklSw9EFHhoF90jetMJqKBM2Q+gTBr8mNeAfPpXf6TMd6dSLrE6tS0v7iwjTg6RCBdcgIGU+suPUlwdeR9GreSEIV8YUHl9d8HQ/kOicda/R82ij7xnVhs4VODUuvFVN4V4ecAJ23efA7kZcWo/MiFzEn8tKitKISciIvLUUVjKQTeWkx2mENcCIvLlQnNBEn8tKSVLBIOJGXlqAZkrwTeWl5OpH1iZWYPDKbXlyOMhRR7/fS6BvwcHm/l+9ETVh6oNsK7gGUwm03XRfYAnqspKMOuE3pRo1AWSYq6UgHyyYcJgC7DqjX8l9W3Ra/vguLv0kMwxRJD+zozR+nvkkX4gyE6Jr50l2jAU+PvpMroi+t8QIM/kX+uDmKrBsD5wmkvs24e3ep+ls27pigpX27Isze4630g4TDxMUqoATOLqGkWfoEcH9Jyerx3eS2NVYaFKeSU3xVNTeC5u1JhY/JCpNYiiuTOActJPHVSKlg/BRWs/AjKF7UFNbLo+Vj8Wm7AK3JXDVCV2C/4sP/8OqP6U5I3zmoqrpzqMD6LYSZw/MhIEsQekmOko7exGpqPb4JY2PX7xQGvI0aE/Jh2mSkfHxe9Vcy8as4gTV7QhznT6QUSyjT6dbCoTYh/RJUjeqtoIXWsqHA+4xxG1NyTgiaZu0aKjwTVbMigzy5qbF5WqxgHT0BvO4uVhZa9TjH7St7Z3y1Uqe5iKA1uiGQhEpmwSjwbBsH0qmoBJARBfZl0lRy/HmySglNd8wqe1WPUPhk42iUg+T8EpRggaWsXHaHoiCw1D4FUw49YX9AxtP48d0m+HVIHCLQq3AJ73Hqe/CJUIIkIsJlMp/65eDJgko/IkieMOit8gOlKAAaM5D9emy4dJTbJak6JHmXGtsVKeg1d0iocEUfpATv4kXcSqtEiRJuNDzYewmtYXvGU3qdel9DN5WPqY+gEsnRHIGS4vKKJokSZiVQ6dzajLS3HKHV8CFdc41cJIhXzC64/aUXm7/Vw1EOLMI0agGwoLxXIaNUn72e7irZU6+pk7b3T77YQVMhTi67PLUekBaWa0QqOnavQTguuayrEKwBpawLVevgcUkRWDcloclAT8BMlEVM7UQVZP8YSL6g111NXKgEIrdI7DbHicuUYuQWiqa6+ycckElu4qKVkaqcqEqd/vLGrqKVxIxXQQqNzIkL1XpXXtfInLhM7XfBtgg10mWbQ2RqvWiz39hMXLIyUgkBx8v3hRGzOTWY37IyOxQKGte40A+Ngk1v8okFqlraMmI5VRHrxq8n8vI0lpEV9RBcsyaUkiqJb3HhV0uh49LF64T7UXpBDR926BULXbuCLldYPMs0TGNSvZKiqriLVaAjOIwZy+mYfaaYyqRdRAnW3yw3wkFw9iPeRXKbZsv5D0FTRkqlAQwntELdJcLpz1YQnSfhXdT0wVoB0RrnjXC5c03qva/GarLit4GVG5tcdsu6EvWksWcu/XD0AT1OdnImYKPbhO0GDWaZHOx4wRts7K5McwI6LgNKFVyH2d+Tyt9kxTYCTFmNVroIQNw26Bzh7gqhpLjjRMXugCvc2gGOUHDEU9gw52riIl7hdp3APMDVoHwzQEUzvufZE++4PZClRL4mWSVH6PGKTHCOVuXya+rDOnF9AUZ1os/rkLCAVnzOJZYdu2m5Mpo5N1Wh+ZDLdX8/8KisdaeV021tV3NKmZ0xG/u+Mg7dpviqU2Idt9DCmcO49Otsej0x01alSxYRgx9mqS+0/DPQ6so/TyO6SIBkE1uGSelM5p+n0LuI2KlFjwGBLcZ974UM3oFr8cpp1o7bB8raLTGfjnNcgsX6W3o7Rjvk3oILtW+xs7oqWRO8HIJajVoixs8ii/5RShfJC92PXX5+C22Mfd32PF98dEyyq+QC1bqL3JiI71+5MlFz1OICTyYpWUzirvz5XnMwZTtQEroDOPBZbz5npDzApqa+xEGpgexfUzeNpmuQrum6KL4xMFHxGlCCOZrUd0VW3S+UW5AQSlM5SJbAydYlRWgc8aT09WSJOGGBCgh5wkfVzy7f5cuCNUPkbDGykDdwGOrImMgGXFOj1UEqXSpnHX86LZ0umovQJMbkdAUa3HOnKVodJOA8RDy8yHKgMg9yepOwAimY1BCU4fX3kfx95uQHkWFMXK4STmEBSU8j316DiDlSYSEP5yuRMQMqLOI1jMAyUA4fqvzpJGx1RbomjCqdjII5m5Q2ksmrDE+ohacoTxUf2CR8NjFBCzMBx7QmMPRjIOmwz2H127L4XR0FzvPG0Y9kKnuYpDQVhCoHeqK+yw+KRA/JAM9hgVUDqikIO2bw3HebQOMem7imseGZl4zEMllnhevYM0BgtsZ9dnrvXODQFCVD64Whs33JFW6sMAqGqauKqsfW0NenBZ4TtH7ELg6sSx7kadJ8ARWPEAYyTpcfbWURMkw8AlzWC22Cz1cMKH1Vf7RReJqeCDkuHkEuXAahSQbOogfsXe/wBzamZkNzUDwi+Og4tXGcQuKBHwUExsTwZ5h4BDhHln3Js/xNAmSYlB2eK072aWIKrVB50cBHQRV0rdCNkcc9mZQonKCTWXRS0HNMYpPjtIQo4eKeHKclA2etruI8NC0BclDck+O0BEgh8c8t08KfYZKsBcNqp3NNL+NVfe8XP8Yyq+BSGXixrUN34KVpli4HVJyL77YwMVjfKYKpqa2C2nDOU8GcQOlDjKeDGPMhvnDBwhLktsKEVcwWMifTmVMsfZidcDKQEyh9iP3gslNOAXECpQ/xhTMDSpDbdv+rmJObhCaCOkfTh/vSm9sl2C0b2Hw1iXhnz0v6H1RWthVRAMMze04EcwKFA7EeX0o/IeAFRJ346db0hLRehtOneRSGOJiM1nM0fbgP58uG3ErjsjnSVu3j8fG8iYDO0fTOrch5PLuTsYIFOH3In3EQXjattIS8AKe/rwSXDYmXekrQvAfegHkSO6MV7F37ok2ruIlAx3z2+8LFrUuQ24pYN67iJoI5xcKzipsI5AQKB+KJ+VRlRDyr0IkAT6BwrUInAjnFwrEKNR4vG2ItoM7RcK6ep4M7QcOHe2rzZB0VXxRgIvBbcoKl4u6N2YzV2HwQuJ5O/uvRmgxmQ2lyieTHKs0LKjdJgaxBivXdBBTuRFTfnga9o4p6dZevYJuW6UjuTKuAUhCQSrhcvmOkd4U1rgykRp0ZWM+1Q3DV22CJewmTpX/hrY9Y2BlFkfae1g0QwCz2Cy8VilInHah1wQC2i5rfptDdt3jGXnwm7JJ2OZcm1WABU0+Mkr164S7QjJ9r2Zi8e3F3tVkETr81f/uyvmurEDxObOntCTiyXcK0e7RQvkjWgS83nRQUkMwmRVACo2pqIuSwBEbVBIVo3FgFv5ud3RzSfif7ey8oX7Ze+f3eNeyzWb+PvaDo+G4SGsGxRip0yjjOKPRZgm9WBzHrQzziPkAr4Nbgfwlv9DeaW0aWEKPE7BrAlgH0avY4TsCrVavHpiBXGSdbljnLUU6aNeEs8u/ASSvI0gOtuwvhLPGfgRmlg33GkedFJ93GumOZpo1fUMkQ9YdfqstAFEV6ciA2v7WKWmB2iYfukaEWWN2WjK49OMmM0R4tWkqX27xQZ4JiwTVziA2iIiKXbR2M4M2PvNAz2hu56lhVF23JjNqT/WoRXdIDHejQFH+rJGgUgY3hIzRqhPkFmb9QFGDWhLE366T0wQj9dLBQ0sGiguAHtFqssJ8mYV+0LetYZh2wl4upgC4haYUcf0Zv72R3cbnj3ALeDrwZTw98QiW5vXYC2EtgWoGHrzq6NN4cQxfMg/2kG2zRc3G0ZShdoM2TjuwLj8ESjC6w2DB0QuR5Av2hDKUP9BN+O2J3Epquw+kGb4ZoIrgLSLogn0Y6KtmJ9tRwLrIKlDihlweagugEih3D8S8PNYPRB9YfpehUL1i/VmSqCtYPLMeKrCkYtDKULtCBe3lrkGDoghlNAWfUB5Q6zQs84uHObv+9BKUT9JgHUrsxtx1B7VooXRx0GQvfQunSoEtIRBZKFwXejKcVvo9M03IvrOwCCM4Vx0Xh1qB0gA7wcZSsgS60KYYcZj3iV0uJqG0IVULr8R6Mjl+TOw0vKKWVxdsbQXEECUz8OAH4VTjc0Y0JQc8A9UU4Lo45x8Fnc0Y8xNULvBEVR9xjCthzKJ2AHTQNtDEOzjDNFBCX4QiEaqYCvgyJL1wzDewFNJ2waf70RDpLBqU3xjQFuKeG4pQ1sC/6SGmC/XAzKL2BsSnATYFwBMcmATeDwhEgmwpgv1azuyNINgXQZTh9gbIpIA76V5LRVLBGNbB9S7MP9+/vfnu4e2hfm/0rYXYbvUaXEi9FOMuBtLbFB8vAboi/4MebB0oM37+fBPRWXJ0NVRDsy93vD3e3kefYl5KliCBFzZnJ4xywGdkdCaWNWTot1HoyeWyWz+m5ZMHee8DHTpHp4dn3vaD+RUNOWUvFwYaUmpQ4Mgxs4wCNdS9ZVe+FjJrkl1lRTbO6HtIKhV1S1EtOdqjAc1zLD3BI2F2vBipCcCnApy78Vbd/kwQN5UZ5rwpvPFRXT6lMAI26AyWvrvRyyhx0b+eIDStR7Oj5OcPErOHulTSlYhijnKgAkrOCml9KB42bFAokZgKbW844OkH+O24SBoy0ZfACY/V4VX24hptjymL2Pv7wiiSt4eaenK9Q1Cpw+dm4+bB3+2x8Hc5LeuFuDrq3N5C5TEfj3H8FJGABcb/9Mpwrk66AuF86MnVdm3gFyP2W6oQWVyZfETKPfNp6c30SFkDzyLheaNcnYwF0r4zHq7MyRwErU/YwrkfGGm5eSZ+RfR55zwBE0hy3qA94TaJWgXP7gJyXdsW6bCyl1PQ6X1QnBj16ZjG/rnOZS652Uxpyp4gxDd1yrVFuPIKTtAJcVOAkeegaRc6hcwkd4rQMg25iihq7hjXZQF6D6B0C8M4QVhTqY91sByF0DbRA4MdBLjpih4b+r0LaNuRcnTv/OBkc12WyW+ELCh8FyCUSBIRTSmn003FAiugQZbhSLnBqV51ams/9yikGYWT+H6KWVJThSpnu/oioTni3THoJPeE3MgmTf8cbrP9naOf/7+7ceuO2sTj+XfY9I2ccO02QLbDIBosCRbFoui/7InAkzgxj3SByYqfAfvcldb+Qh9SMLB0VDeqxh5J+/8OLyEPycCxqHkNt7U18hajbDcXZKSHiki9yXukCNurpeY35jv5yJE60yQa5UG+Ik8AXLmjoc5HmCx2gfpvNlQ9B/upBCnSFUFMMt28EmwoHQxTL3rejuMHVNjSmuuQ09N+EDYzoNw39NyMdEDDV4XOkRau8IfEG+OtcAZtQbSK/wRWwCd0g/g1dLHVk3PI7lGcyg1HIDQZZftPwKxhDu9EYfCO6zqTUT5xtGqW6n8/3OHv3teDmOJMu7qsvVmKop/Ma2/RL48QaqGy5JXkV7ytMUuapSIM0mruKseGd/ZxIQ+Jdqj3AbWe4ABlOBa6+YAN+F4MJDArcurr9e+KsdK6Z79zI6Cy2LeUGBbc1QLMfszAU7PP0kgdARHN9HJ1ekvFeu1EWLx0upa+u2a5a57ImasoQOGfLRu+wEVc8APKBnZLLIufyuEK3RBB2lAarBMWywQ+4IAkXFoVFnHpUAnpU0CET8kcU4SrvXSYIPUBV4CscCPhM5L/9HSrqDpMVPUujZUNROMHXVCA+VfV5+cCMVgF9LkgCukbSqXksNvphgq54wHN3VHb4JPx24cKP6IkEP1bskBuVwJhTBR7zNFbuK/QSu6DOIpVfrriwvAlekRrQSSL5JaM5p2ITQjWwzmI5XzZS7SRxFZyzmJeHuw941dR0djk42w97Y1Fs0MZE3gCB0N8y8rTKygczdoMEgi8bgc0KPYrCNt5qhgn4ZB1pNGEW0PV4x2SQjBAVemjFfcDF+2ABrh2evmAxqnZkBOYi4iIYqi7BCAwSIcewb+/vUJWfLhOEXqy5pUXQJo7K0zsmA2TkLKNx+PYRlXemBwXAqw3wmLhrHhh5//CIDLoigrEXOY93ArTtfN5yXz0y6IoImoXhCaoyXfNYkJ/lvVC9S3tQ0EQG4fTxHSbylggcecYZEW/2uxdM6H0qeODMBVELwpB1wUZgkAiR+2F+QDXQ6DIB6CE9XFBxN0AgNKp+VmidUQ/PqAbQFQ7sEFo2qL3dHzSKbT9ETkSeLhwq3kbdIkHga+1mMWLr96v0oM9P4bJnLlmYax4IWUUBw9ZM96AA+ChG1eRVOJAziMZp/sM/XI5HtZ85ihY+597mHNLjAYISKuTNgicqUOXEAAsSwLjwn55RwbdIAHjKUPlBKxzIJURRve4rHAj4CRXvkxU34LhG9C2RBRuXh7MGskC/xwb93tEnjoq7wwShc4LPk99hglzIuOaQc+sMMrI1FPZVE1wtyCfBGZWnpAdlgy/WzPELE7iG8Do2m5Q0fWL4MqKhsuALpvqM2PBbKgBfnHNKFj/22kLfg4LgWYyNvCECsKsIBpi4O0gAOLalZQ6LyVQSP8hRvZu6THZ0VO1Kl8mKzlF54rpMXXTd1jhbTCVNeA0MUlWAHLdV2+WO2mpNJrnIzzQhh4iicA60MkyEztKqVZtrB7uxKzSAThWqArJlhOXrBbZwljpGnSqW/0jS5AcOZ65RZhdyM1v/lBr3bX+lbJVesKTc5MyxDEo6+aIHdBe20mnE7sLM5xPDwgbhLnGKG0PaBZYrJ5AJaqFcBGBZc90T4LLFsEy7eoQ9QIclhB4oJxH0RXC8bR0MOl0o6ibCDjtdMNrGHga1C5UX5Shcyx1NDZMdH89WxA6/25bDMi2m6ZSOBMcZlTomFq3KITIVPS4HGexPdPW7YXLAF/klwNa9aaHsAjAOUieMRtc7Zgzg158hZgv2NPJ5ReyQk/zHIFyTcbHxCmHVahtUpN4IyDOhN20dAuouixW4nDhGRN0AmdHr6W4M1B0WI3A794SAuAdjRCYROyVrRbobIvdgjMjldowmdj0GcA2SGb8ISCY74fmqk9YNeh/Hho3K6mMkG36crjpLMSCvaByg/ZysumB0DF4TOcLLXPpOuOxe41PRQzPL6YTiw1ULTGBmKYkfX3CwNyRG2Co0GRafZtNj1GOZZdT5g6cWaJBs+M85WTVkygC9xjFjr+47bkcYOk+xeVTkqwfhANdRuYpA1E6aycxixKpOqoZcjBeedDGLrZqobD0mMsLTIGuPoapOpV8bX8dkEYCnWR/ymMHLXZF+lkYoCs2Qxwgexem6e79q4gbEiBqHa8eiq1lbEggWywu+g2LGzTiCyeGGuEcDQq++0bjLrN1kPEJWrqR1Z2y6zC0NCC1y+WgszA2M2d1JQjWUwwDcQTHjPqHqcgxwIGwsjVwHBcBdPZBPi6sN36N12eMqGjooo4RcppZ9Pv9MIxUVGIMADRKIj8n4Qx4j+HDrFyoVIBwsKWJIZlf6NCB0OX5DVAO0UKCEmPFVA110yWsWEFhe+/Ye1UhST+Ug4on+QFNq+kRG+GKHD6YWZwQEvnNrR3RZvRHMPmuhXOZEUdUAE5fFT44hA1oSJ6c+GuIGx6G8Y6Du07hUUiJHr7jIGySnNgZNEddCuUio1kGrkqb6En6ilh4SwQJkqkBOF6E8SsXKJ5gC8jR0TqJEmstLsIlpqVxEqMMecAmoiFzgj8fwjIy+RnLBPxOODb9GcsFXJ4fhoq+IXOCLY1lw0ddILvgqlhEu+orIqeHEZnnubPeig4JgQKBBmtBnwiVAf26iUQKS9aoaJFd8RLOFZrIr+q/IBGnobuuUo5bX53Tt+uGSpDl5DOz64aKvkZy7frjwayQXfEy+MQOWkwwcy3fGRK7db1zwmqOEwe43LnrdQY3G7jdJwjRGszbWTOY6lkAmwrJArN91x8XOnQvR0O2ETMeYbopTDJmYlqoVMdg+PPy1v5c4JyzyxxuKB6nK7rN5wzGPfHWjJazTBa5W/Xudx5tnT8s0fnxcJLwDgFkjWFEJ5zQX5QpCOYJZ6DQgiFxPZBWyWCwBiF0bPECLe6REXPL1ibsc5vVIK9Y7a6Vbu8Y5VTdkde2airZ+LXOsYijqF1C5bKE3sjwVaZBGg1dhL80holBI2rp2y2SLG6DG9+TDvQEIdOABCl4TrD1IMKOU/nS3f/vwziVj2tTr6W0ZPD2WLbeQibAosGfhc3y4cJfcKxKup7l4vDeCsWUXCmozsj1//nwm352avSLhekqLx3sjGFv+oKA2I9vzh7OQPpPoySWL6rTr6a0JPB2SLa8Q4YPsk+N+BWeWQR0Peszv96MMHid5Oe1fBskMJUE90ecZDdhxmXmifndNPt0riL2G2zOieZAgrGpcpOgq99Sio4L0n+jQgzOOKidpchpRwsG2vE5a69j7pyCoL9yRhQ1bafMGAjwr5U2VMYsuJwYatC6pxdaoMrI0k91XPwNPrDBftXx7Vkj0zETAV1e8obr3yogK+lKdfOPU79NctsRqHKvB+kjQd8O1OhahQp24sQmNLekEeV3DYCj4E/IR7qOMrLOK2+aabNR6dybX67I0uHVThr0ZiynDQ+xn6bMUQIVgycmPSZapn8Uz/Tv5PRZDl1ZoegL7UQJHLWCvZ+I9H/9C9nl8BfuojkachtL4fylTaWRZO6Bu7yZcBjJD3tKgKbtW88kq1hsT7p2V0aU4XuYjLNv3k97s46tRlJLpom8sN4K5FxTBcJQMwUZ/mJT3MjmKzNbpmOicgVdVNEs4OK0LjXlxRR2wGxxLVjeEu028HISlCU2GzZDmjhoyU9o80CQaZ3V7z0U3QrSPbYKfN196XZt4nZRSkzdCHvYWYJHLB0+fR6k20LqD3BV2ps4kWL991UFyFTNvi5o76BNFL75/bybFuk1+DnIHR1JtUPhYwRUmOJMkjJY+W2FGA3T5J8rn7JQUq0G2qL0HP1E4EYIWm2u2We4H+A7iWffyWHYAD+nLVpSb2MeytQP20hr9dTHJ5H7dkuufr7KV1OSNkCdWi5AeWbLw6VHziO2iTxS9/IFfM0k2nApmFVz0gjeot+ae2twtuexyDs1G+In53EQaXzxs2kwZPhIwNedXibs2V86bYrQ55Hx1iMjyh5rMlPFD/qnytyv8asnLB4KYS7I2WoSD5Hqcv0HNHfRrXBQbVKzbjO4gd8UjvmcSbjv328kEzRB/owbo8l/totig9h78DS6KDUof4F/rotiIchO7s4vC9OfhPBfzM4nkp5xE9ukrRzdH555Y7d1lbEzeo3YqYM0V/oHkNKZiq4r7/LeVsiuWWfd+7f/SNTnJ5oxFWd3N0z9nvmys7qZ5jjoeJqa7OJztWZ07ap73j399+e2Pr3M+r3NHvR39w5wnkLc31DxNlveTfEvISpF/ZwGVvaTiB0tUtSheHH76neY5C2ednpj2VA23bN7nnDSob1c9qRwBXvICpX7kP+mRXCIhnxmRA416fzmkJA8/V0vQWSQf+/cibsWOM5mY74rvd4lsVj7e7eR/8pKM5GJ4RRxcdiSPd8Vqup0iKz+qT8F+vz/eP+xP8Tt1uUjTKDhLbOCpnO+OuYRXwndZnn6jgdgVcfWS9A95/Wd1fQMkm0voXuHTTnYlAvl/Jj9/bBrWnf/mw+P+7n7/9vHh4fH+w0/vH97fNW+8T/QliC4hDf9NxPlnFstmt6pvPotPd7ssOX3yemlcrnt75XX7K6+7v/K6d47XNS2CQ1rjC+4QXagsFeLsR9Q/p1zIml8sNTqI3Yv8eMu9m5dnxA5l9BeeBt7vX/7z9ctOpHE0/71//eXzl9++fvnq/Vf+eSdexCs+4lfZ+CSc/k6Pb76qlPSXz+YnqsWq0ceQ8iBnmWoffv7kjf9WvpN77Yj82yevqoXy89/+938M/03p=END_SIMPLICITY_STUDIO_METADATA