#include "opendisplay_buzzer.h"
#include "opendisplay_ble.h"
#include "opendisplay_constants.h"
#include "opendisplay_structs.h"
#include "nrf54_gpio.h"

#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <zephyr/kernel.h>

/*
 * Passive buzzer subsystem, ported from the Arduino reference
 * (OpenDisplay-Firmware/src/buzzer_control.cpp).
 *
 * Wire semantics (payload parsing, frequency-index table, 5 s cap, duty
 * handling and error codes) are byte-for-byte identical to the reference
 * handleBuzzerActivate. The only difference is timing: the reference blocks the
 * calling context with micros()/delay() busy-loops for up to 5 s and only then
 * replies. On this Zephyr port the pipe dispatch runs on the main thread (via
 * opendisplay_pipe_process), so blocking it for seconds would stall command
 * processing and the advertising/connection housekeeping. We therefore validate
 * up front, start playback on a non-blocking state machine (identical model to
 * opendisplay_led.c) and let the pipe layer reply immediately -- the response
 * bytes are unchanged. The square wave itself is generated by a self-rescheduling
 * k_timer so an in-flight tone keeps toggling the GPIO without any busy-wait.
 */

_Static_assert(sizeof(struct PassiveBuzzerConfig) == 32,
	       "PassiveBuzzerConfig must be 32 bytes");

#define BUZZER_FREQ_MIN_HZ          400u
#define BUZZER_FREQ_MAX_HZ          12000u
#define BUZZER_DURATION_UNIT_MS     5u
#define BUZZER_INTER_PATTERN_GAP_MS 20u
#define BUZZER_MAX_TOTAL_MS         5000u
#define BUZZER_MAX_PAYLOAD          244u

typedef enum {
	BZ_IDLE = 0,
	BZ_PATTERN_ENTER,
	BZ_STEP,
	BZ_PATTERN_END,
} buzzer_phase_t;

static struct {
	bool active;
	bool waiting;
	uint8_t instance;
	const struct PassiveBuzzerConfig *cfg;
	uint8_t payload[BUZZER_MAX_PAYLOAD];
	uint16_t payload_len;
	uint8_t outer;         /* total repeats of the whole pattern list */
	uint8_t pattern_count;
	uint8_t rep;           /* current repeat */
	uint8_t pattern_idx;   /* current pattern within the list */
	uint16_t poff;         /* read cursor into payload */
	uint8_t step_idx;      /* current step within the pattern */
	uint8_t nsteps;        /* steps in the current pattern */
	uint32_t play_start_ms;
	buzzer_phase_t phase;
	/* Waveform, driven from the tone timer ISR. */
	uint8_t drive_pin;
	bool tone_running;
	bool tone_high;
	uint32_t on_us;
	uint32_t off_us;
} s_bz;

static struct k_timer s_step_timer; /* fires at the end of a tone step / gap */
static struct k_timer s_tone_timer; /* square-wave GPIO toggle */
static volatile bool s_step_due;

static uint32_t buzzer_index_to_hz(uint8_t idx)
{
	if (idx == 0u) {
		return 0u;
	}
	uint32_t span = BUZZER_FREQ_MAX_HZ - BUZZER_FREQ_MIN_HZ;

	return BUZZER_FREQ_MIN_HZ + (span * (uint32_t)(idx - 1u)) / 254u;
}

static void buzzer_set_enable(const struct PassiveBuzzerConfig *b, bool on)
{
	if (b->enable_pin == GPIO_PIN_UNUSED) {
		return;
	}
	bool high = on;

	if ((b->flags & BUZZER_FLAG_ENABLE_ACTIVE_HIGH) == 0u) {
		high = !high;
	}
	nrf54_gpio_write(b->enable_pin, high);
}

static void buzzer_stop_tone(void)
{
	s_bz.tone_running = false;
	k_timer_stop(&s_tone_timer);
	s_bz.tone_high = false;
	if (s_bz.cfg != NULL && s_bz.cfg->drive_pin != GPIO_PIN_UNUSED) {
		nrf54_gpio_write(s_bz.cfg->drive_pin, false);
	}
}

static void buzzer_start_tone(uint32_t hz)
{
	buzzer_stop_tone();
	if (s_bz.cfg == NULL) {
		return;
	}
	s_bz.drive_pin = s_bz.cfg->drive_pin;
	if (hz == 0u) {
		/* Rest / silence: hold the drive line low for the step duration. */
		nrf54_gpio_write(s_bz.drive_pin, false);
		return;
	}

	uint8_t duty = s_bz.cfg->duty_percent;

	if (duty == 0u || duty > 100u) {
		duty = 50u;
	}
	uint32_t period_us = 1000000u / hz;

	if (period_us < 2u) {
		period_us = 2u;
	}
	uint32_t on_us = (period_us * (uint32_t)duty) / 100u;

	if (on_us == 0u) {
		on_us = 1u;
	}
	if (on_us >= period_us) {
		on_us = period_us - 1u;
	}
	s_bz.on_us = on_us;
	s_bz.off_us = period_us - on_us;
	s_bz.tone_high = true;
	s_bz.tone_running = true;
	nrf54_gpio_write(s_bz.drive_pin, true);
	k_timer_start(&s_tone_timer, K_USEC(on_us), K_NO_WAIT);
}

static void buzzer_finish(void)
{
	s_bz.tone_running = false;
	k_timer_stop(&s_tone_timer);
	k_timer_stop(&s_step_timer);
	if (s_bz.cfg != NULL) {
		if (s_bz.cfg->drive_pin != GPIO_PIN_UNUSED) {
			nrf54_gpio_write(s_bz.cfg->drive_pin, false);
		}
		buzzer_set_enable(s_bz.cfg, false);
	}
	memset(&s_bz, 0, sizeof(s_bz));
	s_step_due = false;
}

static void buzzer_schedule_wait_ms(uint32_t ms)
{
	s_bz.waiting = true;
	s_step_due = false;
	if (ms == 0u) {
		s_step_due = true;
		return;
	}
	k_timer_start(&s_step_timer, K_MSEC(ms), K_NO_WAIT);
}

static void buzzer_run_step(void)
{
	if (!s_bz.active) {
		return;
	}
	for (;;) {
		uint32_t now = k_uptime_get_32();

		switch (s_bz.phase) {
		case BZ_PATTERN_ENTER:
			if ((uint32_t)(now - s_bz.play_start_ms) >= BUZZER_MAX_TOTAL_MS) {
				buzzer_finish();
				return;
			}
			if (s_bz.poff >= s_bz.payload_len) {
				buzzer_finish();
				return;
			}
			s_bz.nsteps = s_bz.payload[s_bz.poff++];
			s_bz.step_idx = 0;
			s_bz.phase = BZ_STEP;
			break;

		case BZ_STEP: {
			if (s_bz.step_idx >= s_bz.nsteps) {
				s_bz.phase = BZ_PATTERN_END;
				break;
			}
			uint32_t elapsed = (uint32_t)(now - s_bz.play_start_ms);

			if (elapsed >= BUZZER_MAX_TOTAL_MS) {
				buzzer_finish();
				return;
			}
			if ((uint32_t)s_bz.poff + 2u > s_bz.payload_len) {
				buzzer_finish();
				return;
			}
			uint8_t fidx = s_bz.payload[s_bz.poff++];
			uint8_t dunit = s_bz.payload[s_bz.poff++];
			uint32_t hz = buzzer_index_to_hz(fidx);
			uint32_t ms = (uint32_t)dunit * BUZZER_DURATION_UNIT_MS;
			uint32_t remaining = BUZZER_MAX_TOTAL_MS - elapsed;

			if (ms > remaining) {
				ms = remaining;
			}
			s_bz.step_idx++;
			buzzer_set_enable(s_bz.cfg, true);
			buzzer_start_tone(hz);
			buzzer_schedule_wait_ms(ms);
			return;
		}

		case BZ_PATTERN_END:
			if ((uint32_t)(s_bz.pattern_idx + 1u) < s_bz.pattern_count) {
				s_bz.pattern_idx++;
				s_bz.phase = BZ_PATTERN_ENTER;
				buzzer_schedule_wait_ms(BUZZER_INTER_PATTERN_GAP_MS);
				return;
			}
			s_bz.rep++;
			if (s_bz.rep < s_bz.outer) {
				s_bz.poff = 3u;
				s_bz.pattern_idx = 0;
				s_bz.phase = BZ_PATTERN_ENTER;
				break;
			}
			buzzer_finish();
			return;

		default:
			buzzer_finish();
			return;
		}
	}
}

static void buzzer_step_timer_cb(struct k_timer *timer)
{
	ARG_UNUSED(timer);
	s_step_due = true;
}

static void buzzer_tone_timer_cb(struct k_timer *timer)
{
	ARG_UNUSED(timer);
	if (!s_bz.tone_running) {
		return;
	}
	if (s_bz.tone_high) {
		nrf54_gpio_write(s_bz.drive_pin, false);
		s_bz.tone_high = false;
		k_timer_start(&s_tone_timer, K_USEC(s_bz.off_us), K_NO_WAIT);
	} else {
		nrf54_gpio_write(s_bz.drive_pin, true);
		s_bz.tone_high = true;
		k_timer_start(&s_tone_timer, K_USEC(s_bz.on_us), K_NO_WAIT);
	}
}

void opendisplay_buzzer_init(void)
{
	const struct GlobalConfig *gc = opendisplay_get_global_config();

	k_timer_init(&s_step_timer, buzzer_step_timer_cb, NULL);
	k_timer_init(&s_tone_timer, buzzer_tone_timer_cb, NULL);
	memset(&s_bz, 0, sizeof(s_bz));
	s_step_due = false;

	if (gc == NULL || !gc->loaded || gc->passive_buzzer_count == 0u) {
		return;
	}
	for (uint8_t i = 0; i < gc->passive_buzzer_count; i++) {
		const struct PassiveBuzzerConfig *b = &gc->passive_buzzers[i];

		if (b->drive_pin == GPIO_PIN_UNUSED) {
			continue;
		}
		nrf54_gpio_configure_output(b->drive_pin, false);
		if (b->enable_pin != GPIO_PIN_UNUSED) {
			bool active_high = (b->flags & BUZZER_FLAG_ENABLE_ACTIVE_HIGH) != 0u;

			/* Initialise to the disabled level (active-low -> drive high). */
			nrf54_gpio_configure_output(b->enable_pin, !active_high);
		}
		printf("[OD] buzzer %u drive=0x%02X enable=0x%02X duty=%u\r\n",
		       (unsigned)b->instance_number, (unsigned)b->drive_pin,
		       (unsigned)b->enable_pin, (unsigned)b->duty_percent);
	}
}

int opendisplay_buzzer_activate(const uint8_t *data, uint16_t len)
{
	if (len < 3u) {
		return 1;
	}
	uint8_t inst = data[0];
	const struct GlobalConfig *gc = opendisplay_get_global_config();

	if (gc == NULL || !gc->loaded || inst >= gc->passive_buzzer_count) {
		return 2;
	}
	const struct PassiveBuzzerConfig *b = &gc->passive_buzzers[inst];

	if (b->drive_pin == GPIO_PIN_UNUSED) {
		return 3;
	}

	uint8_t outer = data[1];

	if (outer == 0u) {
		outer = 1u;
	}
	uint8_t pattern_count = data[2];

	if (pattern_count == 0u) {
		return 4;
	}

	/* Validate the whole pattern/step stream before playing anything, exactly
	 * like the reference: every pattern is [nsteps][fidx,dunit]*nsteps and the
	 * declared patterns must consume the payload with no trailing bytes. */
	uint16_t scan = 3u;

	for (uint8_t pi = 0; pi < pattern_count; pi++) {
		if (scan >= len) {
			return 5;
		}
		uint8_t nsteps = data[scan++];
		uint32_t need = (uint32_t)nsteps * 2u;

		if ((uint32_t)scan + need > (uint32_t)len) {
			return 5;
		}
		scan = (uint16_t)(scan + need);
	}
	if (scan != len) {
		return 6;
	}
	if (len > sizeof(s_bz.payload)) {
		/* Payload cannot exceed the pipe MTU, but stay defensive. */
		return 5;
	}

	opendisplay_buzzer_stop();

	memcpy(s_bz.payload, data, len);
	s_bz.payload_len = len;
	s_bz.instance = inst;
	s_bz.cfg = b;
	s_bz.outer = outer;
	s_bz.pattern_count = pattern_count;
	s_bz.rep = 0;
	s_bz.poff = 3u;
	s_bz.pattern_idx = 0;
	s_bz.step_idx = 0;
	s_bz.phase = BZ_PATTERN_ENTER;
	s_bz.play_start_ms = k_uptime_get_32();
	s_bz.waiting = false;
	s_bz.active = true;

	buzzer_run_step();
	return 0;
}

void opendisplay_buzzer_process(void)
{
	if (!s_bz.active) {
		return;
	}
	if (s_bz.waiting) {
		if (!s_step_due) {
			return;
		}
		s_step_due = false;
		s_bz.waiting = false;
		buzzer_stop_tone();
	}
	buzzer_run_step();
}

void opendisplay_buzzer_stop(void)
{
	if (!s_bz.active) {
		return;
	}
	buzzer_finish();
}
