# Auto-picked for xiao_nrf54lm20a/nrf54lm20a/cpuapp (sysbuild-safe).
# gcc 8.2 cannot compile BT LL_ASSERT size-optimized asm (Zephyr 4.x debug.h)
# CONFIG_BT_CTLR_ASSERT_OPTIMIZE_FOR_SIZE is not set
CONFIG_NFC_T2T_NRFXLIB=y
