/********************************************************************
 * Autogenerated file, do not edit.
 * Minimal static GATT: GAP (0x1800) + Device Name only. OpenDisplay
 * service lives in the dynamic GATT database (opendisplay_ble.c).
 *******************************************************************/

#include <stdint.h>
#include "sli_bt_gattdb_def.h"

#define GATT_HEADER(F) F
#define GATT_DATA(F) F
GATT_DATA(const uint16_t gattdb_uuidtable_16_map[]) =
{
  0x2800,
  0x2803,
  0x2a00,
};

GATT_DATA(const uint8_t gattdb_uuidtable_128_map[]) =
{
  0x0 //IAR workaround for empty array
};
GATT_DATA(sli_bt_gattdb_attribute_chrvalue_t gattdb_attribute_field_2) = {
  .properties = 0x0a,
  .max_len = 16,
  .data = { 0x4f, 0x44, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, },
};
GATT_DATA(const sli_bt_gattdb_value_t gattdb_attribute_field_0) = {
  .len = 2,
  .data = { 0x00, 0x18, }
};

GATT_DATA(const sli_bt_gattdb_attribute_t gattdb_attributes_map[]) = {
  { .handle = 0x01, .uuid = 0x0000, .permissions = 0x801, .caps = 0xffff, .state = 0x00, .datatype = 0x00, .constdata = &gattdb_attribute_field_0 },
  { .handle = 0x02, .uuid = 0x0001, .permissions = 0x801, .caps = 0xffff, .state = 0x00, .datatype = 0x05, .characteristic = { .properties = 0x0a, .char_uuid = 0x0002 } },
  { .handle = 0x03, .uuid = 0x0002, .permissions = 0x803, .caps = 0xffff, .state = 0x00, .datatype = 0x01, .dynamicdata = &gattdb_attribute_field_2 },
};

GATT_HEADER(const sli_bt_gattdb_t gattdb) = {
  .attributes = gattdb_attributes_map,
  .attribute_table_size = 3,
  .attribute_num = 3,
  .uuid16 = gattdb_uuidtable_16_map,
  .uuid16_table_size = 3,
  .uuid16_num = 3,
  .uuid128 = gattdb_uuidtable_128_map,
  .uuid128_table_size = 0,
  .uuid128_num = 0,
  .num_ccfg = 0,
  .caps_mask = 0xffff,
  .enabled_caps = 0xffff,
};
const sli_bt_gattdb_t *static_gattdb = &gattdb;
