/********************************************************************
 * Autogenerated file, do not edit.
 * Minimal static GATT: GAP + Device Name only.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_device_name                    3

#define gattdb_device_name_len                13


#endif // __GATT_DB_H
